// StayTW Study — TOCFL Level 1 文法
// 形式: id, cat, t=タイトル, p=文型, ex={j,e,k}=解説, eg=例文[{z,py,j,e,k}]
const GRAMMAR_L1 = [
{id:"l1-1",cat:"基本文型",t:"A 是 B",g:{j:"〜は〜です",e:"A is B",k:"A는 B이다"},p:{j:"A ＋ 是 ＋ B",e:"A + 是 + B",k:"A + 是 + B"},
ex:{j:"「是 shì」は「〜です・〜である」。日本語の「AはBです」にあたる最重要動詞。否定は「不是」。",e:"\"是\" links two nouns: A is B. Negative: 不是.",k:"\"是\"는 'A는 B이다'를 나타내는 동사. 부정은 \"不是\"."},
eg:[{z:"我<em>是</em>日本人。",py:"Wǒ shì Rìběnrén.",j:"私は日本人です。",e:"I am Japanese.",k:"저는 일본인입니다."},{z:"他<em>不是</em>學生。",py:"Tā bú shì xuéshēng.",j:"彼は学生ではありません。",e:"He is not a student.",k:"그는 학생이 아닙니다."}]},
{id:"l1-2",cat:"基本文型",t:"〜嗎？",g:{j:"〜ですか",e:"Is it ~?",k:"~입니까?"},p:{j:"文 ＋ 嗎？",e:"sentence + 嗎？",k:"문장 + 嗎？"},
ex:{j:"文末に「嗎 ma」を付けるだけで疑問文になる。日本語の「〜か？」と同じ感覚。語順は変えない。",e:"Add 嗎 to the end of a statement to make a yes/no question. Word order stays the same.",k:"평서문 끝에 \"嗎\"만 붙이면 의문문이 된다. 어순은 그대로."},
eg:[{z:"你是台灣人<em>嗎</em>？",py:"Nǐ shì Táiwānrén ma?",j:"あなたは台湾人ですか。",e:"Are you Taiwanese?",k:"당신은 대만 사람입니까?"},{z:"這個好吃<em>嗎</em>？",py:"Zhège hǎochī ma?",j:"これはおいしいですか。",e:"Is this tasty?",k:"이거 맛있어요?"}]},
{id:"l1-3",cat:"基本文型",t:"不〜",g:{j:"否定",e:"negation",k:"부정"},p:{j:"不 ＋ 動詞／形容詞",e:"不 + verb/adjective",k:"不 + 동사/형용사"},
ex:{j:"動詞・形容詞の前に「不 bù」を置くと否定。後ろが第4声のとき「不」は第2声（bú）に変調する。※「有」の否定だけは「沒有」。",e:"Put 不 before a verb/adjective to negate it. 不 becomes bú before a 4th tone. Exception: 有 → 沒有.",k:"동사/형용사 앞에 \"不\"를 붙여 부정. 뒤가 4성이면 \"不\"는 2성(bú)으로 변조. 단 \"有\"의 부정은 \"沒有\"."},
eg:[{z:"我<em>不</em>喝酒。",py:"Wǒ bù hē jiǔ.",j:"私はお酒を飲みません。",e:"I don't drink alcohol.",k:"저는 술을 마시지 않습니다."},{z:"今天<em>不</em>熱。",py:"Jīntiān bú rè.",j:"今日は暑くありません。",e:"It's not hot today.",k:"오늘은 덥지 않습니다."}]},
{id:"l1-4",cat:"基本文型",t:"的",g:{j:"〜の",e:"~'s / of",k:"~의"},p:{j:"名詞A ＋ 的 ＋ 名詞B",e:"noun A + 的 + noun B",k:"명사A + 的 + 명사B"},
ex:{j:"「的 de」は日本語の「の」。所有・所属を表す。家族や親しい関係では省略できる（我媽媽＝私の母）。",e:"的 marks possession, like English 's. Often dropped for close relationships (我媽媽 = my mom).",k:"\"的\"는 '~의'. 가족 등 가까운 관계에서는 생략 가능(我媽媽 = 우리 엄마)."},
eg:[{z:"這是我<em>的</em>手機。",py:"Zhè shì wǒ de shǒujī.",j:"これは私の携帯です。",e:"This is my phone.",k:"이것은 제 휴대폰입니다."},{z:"台灣<em>的</em>水果很好吃。",py:"Táiwān de shuǐguǒ hěn hǎochī.",j:"台湾の果物はおいしいです。",e:"Taiwanese fruit is delicious.",k:"대만 과일은 맛있습니다."}]},
{id:"l1-5",cat:"基本文型",t:"很＋形容詞",g:{j:"形容詞述語文",e:"adjectival predicate sentence",k:"형용사 술어문"},p:{j:"主語 ＋ 很 ＋ 形容詞",e:"subject + 很 + adjective",k:"주어 + 很 + 형용사"},
ex:{j:"中国語では形容詞が述語になるとき「是」を使わず、飾りの「很 hěn」を置くのが基本形。この「很」は必ずしも「とても」の意味ではない。",e:"Adjectives don't need 是. Plain statements usually take 很 before the adjective; here 很 doesn't really mean \"very\".",k:"형용사 술어문에는 \"是\"를 쓰지 않고 보통 \"很\"을 앞에 둔다. 이때 \"很\"은 '매우'의 뜻이 약하다."},
eg:[{z:"珍珠奶茶<em>很</em>好喝。",py:"Zhēnzhū nǎichá hěn hǎohē.",j:"タピオカミルクティーはおいしいです。",e:"Bubble tea is tasty.",k:"버블티는 맛있습니다."},{z:"他<em>很</em>忙。",py:"Tā hěn máng.",j:"彼は忙しいです。",e:"He is busy.",k:"그는 바쁩니다."}]},
{id:"l1-6",cat:"基本文型",t:"有／沒有",g:{j:"ある・いる・持っている",e:"there is / to have",k:"있다·가지고 있다"},p:{j:"主語 ＋ 有／沒有 ＋ 名詞",e:"subject + 有/沒有 + noun",k:"주어 + 有/沒有 + 명사"},
ex:{j:"「有 yǒu」は所有（持っている）と存在（ある・いる）の両方を表す。否定は「不有」ではなく必ず「沒有 méiyǒu」。",e:"有 covers both possession and existence. Its negative is always 沒有, never 不有.",k:"\"有\"는 소유와 존재를 모두 나타낸다. 부정은 반드시 \"沒有\"."},
eg:[{z:"我<em>有</em>兩張票。",py:"Wǒ yǒu liǎng zhāng piào.",j:"チケットを2枚持っています。",e:"I have two tickets.",k:"표가 두 장 있습니다."},{z:"這附近<em>沒有</em>便利商店。",py:"Zhè fùjìn méiyǒu biànlì shāngdiàn.",j:"この近くにコンビニはありません。",e:"There's no convenience store nearby.",k:"이 근처에는 편의점이 없습니다."}]},
{id:"l1-7",cat:"基本文型",t:"在",g:{j:"〜にある・〜にいる／〜で",e:"to be at / at (a place)",k:"~에 있다 / ~에서"},p:{j:"A ＋ 在 ＋ 場所 ／ 在 ＋ 場所 ＋ 動詞",e:"A + 在 + place / 在 + place + verb",k:"A + 在 + 장소 / 在 + 장소 + 동사"},
ex:{j:"「在 zài」は①存在「〜にいる／ある」②動作の場所「〜で」の両方に使う。動作の場所は動詞の前に置くのがポイント（日本語と同じ語順！）。",e:"在 marks location: A 在 place (A is at place), or 在 place + verb (do something at place).",k:"\"在\"는 ① 존재(~에 있다) ② 동작 장소(~에서). 장소구는 동사 앞에 온다."},
eg:[{z:"車站<em>在</em>哪裡？",py:"Chēzhàn zài nǎlǐ?",j:"駅はどこですか。",e:"Where is the station?",k:"역은 어디에 있습니까?"},{z:"我<em>在</em>公司吃午餐。",py:"Wǒ zài gōngsī chī wǔcān.",j:"会社で昼ご飯を食べます。",e:"I eat lunch at the office.",k:"저는 회사에서 점심을 먹습니다."}]},
{id:"l1-8",cat:"基本文型",t:"量詞",g:{j:"個・杯・張…",e:"measure words: 個, 杯, 張…",k:"양사: 個·杯·張…"},p:{j:"数字 ＋ 量詞 ＋ 名詞",e:"number + measure word + noun",k:"숫자 + 양사 + 명사"},
ex:{j:"物を数えるときは必ず「数字＋量詞＋名詞」。日本語の「〜個・〜枚・〜杯」と同じ発想。迷ったら万能量詞「個 ge」でOK。「二」は量詞の前で「兩 liǎng」になる。",e:"Nouns need a measure word after the number: 一杯茶 (a cup of tea). When unsure, use 個. \"Two\" becomes 兩 before measure words.",k:"수사+양사+명사 순서. 모르면 만능 양사 \"個\". 양사 앞에서 '2'는 \"兩\"이 된다."},
eg:[{z:"一<em>杯</em>咖啡、兩<em>個</em>包子。",py:"Yì bēi kāfēi, liǎng ge bāozi.",j:"コーヒー1杯と肉まん2個。",e:"One coffee and two baozi.",k:"커피 한 잔과 만두 두 개."},{z:"我要買三<em>張</em>票。",py:"Wǒ yào mǎi sān zhāng piào.",j:"チケットを3枚買いたいです。",e:"I want to buy three tickets.",k:"표를 세 장 사려고 합니다."}]},
{id:"l1-9",cat:"疑問",t:"疑問詞疑問文",g:{j:"什麼・誰・哪裡",e:"what, who, where",k:"무엇·누구·어디"},p:{j:"聞きたい場所に疑問詞を入れる",e:"Put the question word where the answer would go",k:"묻고 싶은 자리에 의문사를 넣는다"},
ex:{j:"疑問詞（什麼・誰・哪裡・幾・多少）は答えが入る位置にそのまま置く。語順を変えない＆「嗎」は付けない。",e:"Question words stay in the position of the answer. Don't move them and don't add 嗎.",k:"의문사는 대답이 들어갈 자리에 그대로 둔다. 어순 변경 없음, \"嗎\" 불필요."},
eg:[{z:"你叫<em>什麼</em>名字？",py:"Nǐ jiào shénme míngzi?",j:"お名前は何ですか。",e:"What's your name?",k:"이름이 뭐예요?"},{z:"你想去<em>哪裡</em>？",py:"Nǐ xiǎng qù nǎlǐ?",j:"どこへ行きたいですか。",e:"Where do you want to go?",k:"어디에 가고 싶어요?"}]},
{id:"l1-10",cat:"疑問",t:"呢",g:{j:"〜は？",e:"And ~? / What about ~?",k:"~는요?"},p:{j:"名詞 ＋ 呢？",e:"noun + 呢？",k:"명사 + 呢？"},
ex:{j:"「呢 ne」は前の話題を受けて「〜は？」と聞き返す。「我是工程師，你呢？（私はエンジニアです。あなたは？）」のように便利。",e:"呢 bounces the question back: 你呢? = \"And you?\"",k:"\"呢\"는 앞의 화제를 받아 '~는요?'라고 되묻는 말."},
eg:[{z:"我喝茶，你<em>呢</em>？",py:"Wǒ hē chá, nǐ ne?",j:"私はお茶にします。あなたは？",e:"I'll have tea. And you?",k:"저는 차 마실게요. 당신은요?"},{z:"我的手機<em>呢</em>？",py:"Wǒ de shǒujī ne?",j:"私の携帯は（どこ）？",e:"Where's my phone?",k:"내 휴대폰은 어디 있지?"}]},
{id:"l1-11",cat:"疑問",t:"A不A疑問文",g:{j:"反復疑問文",e:"A-not-A question",k:"정반 의문문"},p:{j:"動詞／形容詞 ＋ 不 ＋ 動詞／形容詞",e:"verb/adjective + 不 + verb/adjective",k:"동사/형용사 + 不 + 동사/형용사"},
ex:{j:"「好不好？」「要不要？」のように肯定＋否定を並べる疑問文。「嗎」と同じ意味だが、より口語的で台湾で超頻出。",e:"Repeat verb + 不 + verb: 要不要? = \"Do you want it or not?\" Very common in Taiwan.",k:"긍정+부정을 나란히 놓는 의문문. \"嗎\"와 같은 뜻이며 대만에서 매우 자주 쓴다."},
eg:[{z:"你<em>要不要</em>加珍珠？",py:"Nǐ yào bú yào jiā zhēnzhū?",j:"タピオカをトッピングしますか。",e:"Do you want to add pearls?",k:"타피오카 추가할래요?"},{z:"這樣<em>好不好</em>？",py:"Zhèyàng hǎo bù hǎo?",j:"これでいいですか。",e:"Is this OK?",k:"이렇게 하면 돼요?"}]},
{id:"l1-12",cat:"助動詞",t:"要",g:{j:"〜が欲しい・〜するつもり",e:"to want / be going to",k:"~을 원하다 / ~할 것이다"},p:{j:"要 ＋ 名詞／動詞",e:"要 + noun/verb",k:"要 + 명사/동사"},
ex:{j:"「要 yào」＋名詞＝「〜をください」、＋動詞＝「〜するつもり・〜する予定」。注文で一番使う単語。断るときは「不用 búyòng（要りません）」が自然。",e:"要 + noun = \"I'll take...\"; 要 + verb = \"going to\". To decline, say 不用 (no need), not 不要.",k:"\"要\"+명사 = ~주세요, +동사 = ~할 것이다. 거절할 때는 \"不用\"이 자연스럽다."},
eg:[{z:"我<em>要</em>一杯大冰奶。",py:"Wǒ yào yì bēi dà bīng nǎi.",j:"アイスミルクティーのLを一つください。",e:"I'll take a large iced milk tea.",k:"라지 아이스 밀크티 한 잔 주세요."},{z:"我明天<em>要</em>去台中。",py:"Wǒ míngtiān yào qù Táizhōng.",j:"明日、台中へ行く予定です。",e:"I'm going to Taichung tomorrow.",k:"내일 타이중에 갈 거예요."}]},
{id:"l1-13",cat:"助動詞",t:"想",g:{j:"〜したい",e:"would like to",k:"~하고 싶다"},p:{j:"想 ＋ 動詞",e:"想 + verb",k:"想 + 동사"},
ex:{j:"「想 xiǎng」は願望「〜したい」。「要」より柔らかく、実行が決まっていないニュアンス。日本語の「〜したいなあ」に近い。",e:"想 + verb = \"would like to\". Softer and less definite than 要.",k:"\"想\"+동사 = ~하고 싶다. \"要\"보다 부드럽고 덜 확정적."},
eg:[{z:"我<em>想</em>學台語。",py:"Wǒ xiǎng xué Táiyǔ.",j:"台湾語を習ってみたいです。",e:"I'd like to learn Taiwanese (Hokkien).",k:"대만어를 배워 보고 싶어요."},{z:"你<em>想</em>吃什麼？",py:"Nǐ xiǎng chī shénme?",j:"何が食べたいですか。",e:"What would you like to eat?",k:"뭐 먹고 싶어요?"}]},
{id:"l1-14",cat:"助動詞",t:"會",g:{j:"（習得して）できる",e:"can (learned skill)",k:"(배워서) 할 수 있다"},p:{j:"會 ＋ 動詞",e:"會 + verb",k:"會 + 동사"},
ex:{j:"「會 huì」は練習・学習して身につけた「できる」。言語・料理・運転など。未来の推測「〜だろう・〜するはず」の意味もある。",e:"會 = can (learned skill): languages, cooking, driving. Also marks future likelihood.",k:"\"會\"는 배워서 할 수 있는 능력. 미래 추측(~할 것이다)의 뜻도 있다."},
eg:[{z:"我<em>會</em>說日文和一點中文。",py:"Wǒ huì shuō Rìwén hàn yìdiǎn Zhōngwén.",j:"日本語と少しの中国語が話せます。",e:"I speak Japanese and a little Chinese.",k:"일본어와 중국어를 조금 할 수 있어요."},{z:"明天<em>會</em>下雨嗎？",py:"Míngtiān huì xiàyǔ ma?",j:"明日は雨が降るでしょうか。",e:"Will it rain tomorrow?",k:"내일 비가 올까요?"}]},
{id:"l1-15",cat:"助動詞",t:"可以",g:{j:"〜してもいい",e:"may / be allowed to",k:"~해도 된다"},p:{j:"可以 ＋ 動詞",e:"可以 + verb",k:"可以 + 동사"},
ex:{j:"「可以 kěyǐ」は許可「〜してもいい」。「可以〜嗎？」で「〜してもいいですか」と丁寧に許可を求められる。",e:"可以 = may / be allowed to. 可以〜嗎? politely asks for permission.",k:"\"可以\" = ~해도 된다. \"可以~嗎?\"로 정중하게 허락을 구한다."},
eg:[{z:"<em>可以</em>試穿嗎？",py:"Kěyǐ shìchuān ma?",j:"試着してもいいですか。",e:"May I try it on?",k:"입어 봐도 돼요?"},{z:"這裡<em>可以</em>拍照。",py:"Zhèlǐ kěyǐ pāizhào.",j:"ここは写真を撮ってもいいです。",e:"You may take photos here.",k:"여기서는 사진을 찍어도 됩니다."}]},
{id:"l1-16",cat:"アスペクト",t:"了",g:{j:"完了・変化",e:"completion / change of state",k:"완료·변화"},p:{j:"動詞 ＋ 了 ／ 文末 ＋ 了",e:"verb + 了 / sentence-final + 了",k:"동사 + 了 / 문말 + 了"},
ex:{j:"「了 le」は①動詞の後＝動作の完了「〜した」②文末＝状況の変化「〜になった」。過去形ではなく「完了・変化」のマーカーと考えるのがコツ。",e:"了 after a verb = completed action; at sentence end = change of state. It is NOT a past tense.",k:"\"了\"는 동사 뒤 = 완료, 문말 = 상태 변화. 과거형이 아니라는 점이 핵심."},
eg:[{z:"我買<em>了</em>三包鳳梨酥。",py:"Wǒ mǎi le sān bāo fènglísū.",j:"パイナップルケーキを3箱買いました。",e:"I bought three boxes of pineapple cakes.",k:"펑리수를 세 상자 샀습니다."},{z:"我吃飽<em>了</em>。",py:"Wǒ chībǎo le.",j:"お腹いっぱいになりました。",e:"I'm full now.",k:"배불러요."}]},
{id:"l1-17",cat:"アスペクト",t:"過",g:{j:"〜したことがある",e:"have done before",k:"~한 적이 있다"},p:{j:"動詞 ＋ 過",e:"verb + 過",k:"동사 + 過"},
ex:{j:"「過 guò」は経験「〜したことがある」。否定は「沒＋動詞＋過」。日本旅行の話などで大活躍。",e:"Verb + 過 = have done before (experience). Negative: 沒 + verb + 過.",k:"동사+\"過\" = ~한 적이 있다. 부정은 \"沒~過\"."},
eg:[{z:"你去<em>過</em>九份嗎？",py:"Nǐ qù guò Jiǔfèn ma?",j:"九份へ行ったことがありますか。",e:"Have you been to Jiufen?",k:"지우펀에 가 본 적 있어요?"},{z:"我沒吃<em>過</em>臭豆腐。",py:"Wǒ méi chī guò chòudòufu.",j:"臭豆腐は食べたことがありません。",e:"I've never eaten stinky tofu.",k:"취두부는 먹어 본 적이 없어요."}]},
{id:"l1-18",cat:"前置詞",t:"跟／和",g:{j:"〜と",e:"with / and",k:"~와/과"},p:{j:"A ＋ 跟／和 ＋ B",e:"A + 跟/和 + B",k:"A + 跟/和 + B"},
ex:{j:"「跟 gēn」「和 hàn」は「〜と」。台湾では「和」を hàn と読むのが特徴（中国では hé）。会話では「跟」のほうがよく使う。",e:"跟 / 和 = \"with; and\". In Taiwan 和 is read hàn (not hé). 跟 is more common in speech.",k:"\"跟/和\" = ~와/과. 대만에서는 \"和\"를 hàn으로 읽는다. 회화에서는 \"跟\"이 더 흔하다."},
eg:[{z:"我<em>跟</em>朋友去逛夜市。",py:"Wǒ gēn péngyǒu qù guàng yèshì.",j:"友達と夜市をぶらぶらしに行きます。",e:"I stroll the night market with friends.",k:"친구와 야시장 구경을 갑니다."},{z:"我要珍珠<em>和</em>椰果。",py:"Wǒ yào zhēnzhū hàn yēguǒ.",j:"タピオカとナタデココをお願いします。",e:"I'd like pearls and nata de coco.",k:"타피오카와 코코넛 젤리 주세요."}]},
{id:"l1-19",cat:"依頼",t:"請",g:{j:"どうぞ・〜してください",e:"please (do)",k:"~해 주세요"},p:{j:"請 ＋ 動詞",e:"請 + verb",k:"請 + 동사"},
ex:{j:"「請 qǐng」を文頭に置くと丁寧な依頼「〜してください」。「請坐（どうぞ座って）」「請給我〜（〜をください）」は初日から使える。",e:"請 + verb = polite request. 請給我〜 = \"Please give me...\".",k:"\"請\"+동사 = 정중한 부탁. \"請給我~\" = ~을 주세요."},
eg:[{z:"<em>請</em>給我菜單。",py:"Qǐng gěi wǒ càidān.",j:"メニューをください。",e:"Please give me the menu.",k:"메뉴판 좀 주세요."},{z:"<em>請</em>再說一次。",py:"Qǐng zài shuō yí cì.",j:"もう一度言ってください。",e:"Please say it again.",k:"다시 한번 말해 주세요."}]},
{id:"l1-20",cat:"アスペクト",t:"在＋動詞",g:{j:"〜している最中",e:"in the middle of doing",k:"~하고 있는 중"},p:{j:"主語 ＋ 在 ＋ 動詞",e:"subject + 在 + verb",k:"주어 + 在 + 동사"},
ex:{j:"動詞の前の「在 zài」は進行「〜しているところ」。「正在」にするとより「まさに今」感が強まる。",e:"在 before a verb marks an action in progress (= -ing). 正在 emphasizes \"right now\".",k:"동사 앞의 \"在\"는 진행(~하고 있다). \"正在\"는 '바로 지금'을 강조."},
eg:[{z:"我<em>在</em>學中文。",py:"Wǒ zài xué Zhōngwén.",j:"中国語を勉強しているところです。",e:"I'm studying Chinese.",k:"중국어를 공부하고 있어요."},{z:"他<em>正在</em>開會。",py:"Tā zhèngzài kāihuì.",j:"彼はちょうど会議中です。",e:"He's in a meeting right now.",k:"그는 지금 회의 중입니다."}]},
];
if (typeof module !== "undefined") module.exports = { GRAMMAR_L1 };
