// 日本語と台湾華語で「同じ漢字なのに意味が違う」語（日中同形異義語・台湾の読み方）。
// 形式: tw=台湾華語の表記, jp=日本語の表記(台湾と字形が違う時だけ), py=拼音(台湾読み),
//       m={ja:{jp,tw}, en:{jp,tw}}=それぞれの意味, ex={z,py,ja,en}=台湾華語の例文
// ⚠️ 台湾の意味・読みは母語者(作者)確認済み。中国との差には触れない(サイト方針)。
const KANJI_GAP = [
{tw:"手紙",py:"shǒu zhǐ",m:{ja:{jp:"手紙（レター）",tw:"トイレットペーパー"},en:{jp:"a letter",tw:"toilet paper"}},ex:{z:"廁所沒有手紙了。",py:"Cèsuǒ méiyǒu shǒuzhǐ le.",ja:"トイレにトイレットペーパーがありません。",en:"There's no toilet paper in the bathroom."}},
{tw:"娘",py:"niáng",m:{ja:{jp:"むすめ",tw:"母（古風）／「女っぽい」"},en:{jp:"daughter",tw:"mother (old-fashioned) / effeminate"}},ex:{z:"他講話有點娘。",py:"Tā jiǎnghuà yǒudiǎn niáng.",ja:"彼の話し方はちょっと女っぽい。",en:"He talks in a slightly effeminate way."}},
{tw:"勉強",py:"miǎn qiǎng",m:{ja:{jp:"勉強する",tw:"無理をする／しぶしぶ"},en:{jp:"to study",tw:"to force oneself / reluctantly"}},ex:{z:"不想吃就別勉強。",py:"Bù xiǎng chī jiù bié miǎnqiǎng.",ja:"食べたくないなら無理しなくていいよ。",en:"If you don't want to eat, don't force yourself."}},
{tw:"大丈夫",py:"dà zhàng fū",m:{ja:{jp:"問題ない、OK",tw:"立派な男、男らしい人"},en:{jp:"it's fine / OK",tw:"a real man"}},ex:{z:"他是個大丈夫，說到就做到。",py:"Tā shì ge dàzhàngfū, shuōdào jiù zuòdào.",ja:"彼は男らしい人で、言ったことは必ずやる。",en:"He's a real man; he does what he says."}},
{tw:"老婆",py:"lǎo pó",m:{ja:{jp:"おばあさん、老いた女性",tw:"妻、奥さん"},en:{jp:"an old woman",tw:"wife"}},ex:{z:"我老婆是台灣人。",py:"Wǒ lǎopó shì Táiwānrén.",ja:"私の妻は台湾人です。",en:"My wife is Taiwanese."}},
{tw:"丈夫",py:"zhàng fū",m:{ja:{jp:"頑丈、丈夫な",tw:"夫"},en:{jp:"sturdy, durable",tw:"husband"}},ex:{z:"她的丈夫在日本工作。",py:"Tā de zhàngfū zài Rìběn gōngzuò.",ja:"彼女の夫は日本で働いています。",en:"Her husband works in Japan."}},
{tw:"先生",py:"xiān shēng",m:{ja:{jp:"教師、医者",tw:"〜さん（男性）／夫"},en:{jp:"teacher, doctor",tw:"Mr. / husband"}},ex:{z:"林先生，請這邊坐。",py:"Lín xiānshēng, qǐng zhèbiān zuò.",ja:"林さん、こちらへどうぞ。",en:"Mr. Lin, please sit here."}},
{tw:"新聞",py:"xīn wén",m:{ja:{jp:"新聞紙",tw:"ニュース"},en:{jp:"newspaper",tw:"the news"}},ex:{z:"你看到今天的新聞了嗎？",py:"Nǐ kàndào jīntiān de xīnwén le ma?",ja:"今日のニュース見た？",en:"Did you see today's news?"}},
{tw:"汽車",py:"qì chē",m:{ja:{jp:"蒸気機関車、列車",tw:"自動車"},en:{jp:"steam train",tw:"car"}},ex:{z:"台北停汽車很難。",py:"Táiběi tíng qìchē hěn nán.",ja:"台北で車を停めるのは難しい。",en:"Parking a car in Taipei is hard."}},
{tw:"走",py:"zǒu",m:{ja:{jp:"走る",tw:"歩く／去る"},en:{jp:"to run",tw:"to walk / to leave"}},ex:{z:"我們走路去捷運站吧。",py:"Wǒmen zǒulù qù jiéyùn zhàn ba.",ja:"歩いてMRTの駅まで行こう。",en:"Let's walk to the MRT station."}},
{tw:"湯",py:"tāng",m:{ja:{jp:"お湯",tw:"スープ"},en:{jp:"hot water",tw:"soup"}},ex:{z:"這碗湯很好喝。",py:"Zhè wǎn tāng hěn hǎohē.",ja:"このスープ、おいしい。",en:"This soup is delicious."}},
{tw:"床",py:"chuáng",m:{ja:{jp:"床（ゆか）",tw:"ベッド"},en:{jp:"floor",tw:"bed"}},ex:{z:"我每天七點起床。",py:"Wǒ měitiān qī diǎn qǐchuáng.",ja:"毎日7時に起きます。",en:"I get up at seven every day."}},
{tw:"結束",py:"jié shù",m:{ja:{jp:"団結する",tw:"終わる"},en:{jp:"to unite",tw:"to end, to finish"}},ex:{z:"電影幾點結束？",py:"Diànyǐng jǐ diǎn jiéshù?",ja:"映画は何時に終わる？",en:"What time does the movie end?"}},
{tw:"經理",jp:"経理",py:"jīng lǐ",m:{ja:{jp:"会計・経理",tw:"マネージャー、部長"},en:{jp:"accounting",tw:"manager"}},ex:{z:"我們經理人很好。",py:"Wǒmen jīnglǐ rén hěn hǎo.",ja:"うちのマネージャーはいい人です。",en:"Our manager is a nice person."}},
{tw:"檢討",jp:"検討",py:"jiǎn tǎo",m:{ja:{jp:"検討する",tw:"反省する、振り返る"},en:{jp:"to consider",tw:"to reflect on one's mistakes"}},ex:{z:"這次失敗要好好檢討。",py:"Zhè cì shībài yào hǎohǎo jiǎntǎo.",ja:"今回の失敗はしっかり反省しないと。",en:"We need to reflect on this failure."}},
{tw:"深刻",py:"shēn kè",m:{ja:{jp:"深刻な、重大な",tw:"印象深い、深い"},en:{jp:"serious, grave",tw:"deep, profound (impression)"}},ex:{z:"這部電影讓我印象很深刻。",py:"Zhè bù diànyǐng ràng wǒ yìnxiàng hěn shēnkè.",ja:"この映画はとても印象に残った。",en:"This movie left a deep impression on me."}},
{tw:"迷惑",py:"mí huò",m:{ja:{jp:"迷惑、困らせる",tw:"戸惑う、惑わされる"},en:{jp:"a nuisance",tw:"to be confused / misled"}},ex:{z:"別被廣告迷惑了。",py:"Bié bèi guǎnggào míhuò le.",ja:"広告に惑わされないで。",en:"Don't be misled by the ads."}},
{tw:"怪我",py:"guài wǒ",m:{ja:{jp:"けが",tw:"私を責める"},en:{jp:"an injury",tw:"blame me"}},ex:{z:"遲到別怪我，是捷運誤點。",py:"Chídào bié guài wǒ, shì jiéyùn wùdiǎn.",ja:"遅刻を私のせいにしないで、MRTが遅れたの。",en:"Don't blame me for being late; the MRT was delayed."}},
{tw:"人參",jp:"人参",py:"rén shēn",m:{ja:{jp:"にんじん",tw:"高麗人参"},en:{jp:"carrot",tw:"ginseng"}},ex:{z:"人參雞湯很補。",py:"Rénshēn jītāng hěn bǔ.",ja:"高麗人参入りのチキンスープは体にいい。",en:"Ginseng chicken soup is nourishing."}},
{tw:"邪魔",py:"xié mó",m:{ja:{jp:"邪魔、妨げ",tw:"悪魔、魔物"},en:{jp:"a hindrance",tw:"a demon"}},ex:{z:"故事裡的邪魔被打敗了。",py:"Gùshì lǐ de xiémó bèi dǎbài le.",ja:"物語の中の悪魔は倒された。",en:"The demon in the story was defeated."}},
{tw:"留守",py:"liú shǒu",m:{ja:{jp:"不在、家を空ける",tw:"残って守る、留まる"},en:{jp:"being away from home",tw:"to stay behind and hold the fort"}},ex:{z:"過年大家回家，我留守辦公室。",py:"Guònián dàjiā huíjiā, wǒ liúshǒu bàngōngshì.",ja:"旧正月はみんな帰省して、私はオフィスに残った。",en:"Everyone went home for New Year; I stayed behind at the office."}},
{tw:"暗算",py:"àn suàn",m:{ja:{jp:"暗算（計算）",tw:"陰で企む、陥れる"},en:{jp:"mental arithmetic",tw:"to plot against someone"}},ex:{z:"小心被人暗算。",py:"Xiǎoxīn bèi rén ànsuàn.",ja:"陰で陥れられないよう気をつけて。",en:"Be careful not to get set up."}},
{tw:"告訴",py:"gào sù",m:{ja:{jp:"告訴する（法律）",tw:"伝える、教える"},en:{jp:"to file a lawsuit",tw:"to tell"}},ex:{z:"告訴我你的名字。",py:"Gàosù wǒ nǐ de míngzi.",ja:"名前を教えて。",en:"Tell me your name."}},
{tw:"出世",py:"chū shì",m:{ja:{jp:"出世する、昇進",tw:"生まれる"},en:{jp:"career success",tw:"to be born"}},ex:{z:"孩子還沒出世。",py:"Háizi hái méi chūshì.",ja:"子どもはまだ生まれていない。",en:"The baby hasn't been born yet."}},
{tw:"中古",py:"zhōng gǔ",m:{ja:{jp:"中古品",tw:"中世（歴史）"},en:{jp:"second-hand",tw:"the Middle Ages"}},ex:{z:"中古歐洲的城堡。",py:"Zhōnggǔ Ōuzhōu de chéngbǎo.",ja:"中世ヨーロッパの城。",en:"A castle from medieval Europe."}},
{tw:"心中",py:"xīn zhōng",m:{ja:{jp:"心中（一緒に死ぬ）",tw:"心の中"},en:{jp:"double suicide",tw:"in one's heart"}},ex:{z:"他心中有很多想法。",py:"Tā xīnzhōng yǒu hěn duō xiǎngfǎ.",ja:"彼の心の中にはいろんな考えがある。",en:"He has many thoughts in his heart."}},
{tw:"上手",py:"shàng shǒu",m:{ja:{jp:"上手い、得意",tw:"慣れる、コツをつかむ"},en:{jp:"skilled",tw:"to get the hang of"}},ex:{z:"新工作很快就上手了。",py:"Xīn gōngzuò hěn kuài jiù shàngshǒu le.",ja:"新しい仕事にすぐ慣れた。",en:"I got the hang of the new job quickly."}},
{tw:"便宜",py:"pián yí",m:{ja:{jp:"便宜、都合",tw:"安い"},en:{jp:"convenience",tw:"cheap"}},ex:{z:"夜市的東西很便宜。",py:"Yèshì de dōngxi hěn piányí.",ja:"夜市の物は安い。",en:"Things at the night market are cheap."}},
{tw:"約束",py:"yuē shù",m:{ja:{jp:"約束",tw:"縛る、制限する"},en:{jp:"a promise",tw:"to restrain, to bind"}},ex:{z:"父母不該約束太多。",py:"Fùmǔ bù gāi yuēshù tài duō.",ja:"親はあまり縛りすぎないほうがいい。",en:"Parents shouldn't restrict too much."}},
{tw:"用心",py:"yòng xīn",m:{ja:{jp:"用心する、警戒",tw:"心を込める、一生懸命"},en:{jp:"caution",tw:"to put one's heart into"}},ex:{z:"她做菜很用心。",py:"Tā zuòcài hěn yòngxīn.",ja:"彼女は料理に心を込めている。",en:"She cooks with great care."}},
{tw:"節目",py:"jié mù",m:{ja:{jp:"節目、区切り",tw:"番組"},en:{jp:"a turning point",tw:"a TV program"}},ex:{z:"這個節目很好笑。",py:"Zhège jiémù hěn hǎoxiào.",ja:"この番組、すごく面白い。",en:"This show is really funny."}},
{tw:"主人",py:"zhǔ rén",m:{ja:{jp:"夫、ご主人",tw:"持ち主、ホスト"},en:{jp:"husband",tw:"owner, host"}},ex:{z:"這隻狗的主人是誰？",py:"Zhè zhī gǒu de zhǔrén shì shéi?",ja:"この犬の飼い主は誰？",en:"Who is this dog's owner?"}},
{tw:"看病",py:"kàn bìng",m:{ja:{jp:"看病する（世話）",tw:"診察を受ける、病院に行く"},en:{jp:"to nurse someone",tw:"to see a doctor"}},ex:{z:"我下午要去看病。",py:"Wǒ xiàwǔ yào qù kànbìng.",ja:"午後、病院に行きます。",en:"I'm going to see a doctor this afternoon."}},
{tw:"麻雀",py:"má què",m:{ja:{jp:"麻雀（マージャン）",tw:"すずめ"},en:{jp:"mahjong",tw:"sparrow"}},ex:{z:"樹上有兩隻麻雀。",py:"Shù shàng yǒu liǎng zhī máquè.",ja:"木の上にすずめが2羽いる。",en:"There are two sparrows in the tree."}},
{tw:"是非",py:"shì fēi",m:{ja:{jp:"ぜひ",tw:"善悪／もめごと、噂"},en:{jp:"by all means",tw:"right and wrong / gossip, trouble"}},ex:{z:"少說是非。",py:"Shǎo shuō shìfēi.",ja:"人の噂話はやめよう。",en:"Don't gossip."}},
{tw:"安靜",jp:"安静",py:"ān jìng",m:{ja:{jp:"安静にする（療養）",tw:"静か"},en:{jp:"bed rest",tw:"quiet"}},ex:{z:"圖書館要保持安靜。",py:"Túshūguǎn yào bǎochí ānjìng.",ja:"図書館では静かにしましょう。",en:"Keep quiet in the library."}},
{tw:"得意",py:"dé yì",m:{ja:{jp:"得意、上手",tw:"誇らしい、得意げ"},en:{jp:"good at",tw:"proud, pleased with oneself"}},ex:{z:"他考了第一名，很得意。",py:"Tā kǎo le dì yī míng, hěn déyì.",ja:"彼は1位を取って得意げだ。",en:"He came first and is very pleased with himself."}},
{tw:"天井",py:"tiān jǐng",m:{ja:{jp:"天井（てんじょう）",tw:"中庭、吹き抜け"},en:{jp:"ceiling",tw:"courtyard, atrium"}},ex:{z:"老房子中間有個天井。",py:"Lǎo fángzi zhōngjiān yǒu ge tiānjǐng.",ja:"古い家の真ん中に中庭がある。",en:"The old house has a courtyard in the middle."}},
{tw:"階段",py:"jiē duàn",m:{ja:{jp:"階段（かいだん）",tw:"段階、ステージ"},en:{jp:"stairs",tw:"a stage, a phase"}},ex:{z:"現在還在學習階段。",py:"Xiànzài hái zài xuéxí jiēduàn.",ja:"今はまだ学習の段階です。",en:"I'm still in the learning phase."}},
{tw:"豬",jp:"猪",py:"zhū",m:{ja:{jp:"イノシシ",tw:"豚"},en:{jp:"wild boar",tw:"pig"}},ex:{z:"我喜歡吃豬肉。",py:"Wǒ xǐhuān chī zhūròu.",ja:"豚肉が好きです。",en:"I like pork."}},
];
if (typeof window !== "undefined") window.KANJI_GAP = KANJI_GAP;
