// StayTW Study — 生活会話フレーズ（台湾のリアルな場面別）
// t: "travel"=旅行者向け / "life"=台湾暮らし向け / "both"=共通
// 形式: cat={j,e,k}, items[{z,py,m:{j,e,k},note:{j,e,k}?}]
const PHRASES_L1 = [
{icon:"👋",t:"both",cat:{j:"あいさつ・自己紹介",e:"Greetings & Introductions",k:"인사・자기소개"},items:[
{z:"你好！",py:"Nǐ hǎo!",m:{j:"こんにちは！",e:"Hello!",k:"안녕하세요!"}},
{z:"早安！",py:"Zǎo'ān!",m:{j:"おはよう！",e:"Good morning!",k:"좋은 아침이에요!"},note:{j:"台湾では「早！」だけでもOK。",e:"In Taiwan just \"早!\" also works.",k:"대만에서는 \"早!\"만 해도 된다."}},
{z:"我叫山田，我是日本人。",py:"Wǒ jiào Shāntián, wǒ shì Rìběnrén.",m:{j:"山田といいます。日本人です。",e:"My name is Yamada. I'm Japanese.",k:"야마다라고 합니다. 일본인입니다."}},
{z:"很高興認識你！",py:"Hěn gāoxìng rènshì nǐ!",m:{j:"お会いできてうれしいです！",e:"Nice to meet you!",k:"만나서 반갑습니다!"}},
{z:"我在學中文，請多多指教。",py:"Wǒ zài xué Zhōngwén, qǐng duōduō zhǐjiào.",m:{j:"中国語を勉強しています。よろしくお願いします。",e:"I'm learning Chinese. Please be patient with me.",k:"중국어를 배우고 있어요. 잘 부탁드립니다."}},
{z:"你吃飽了嗎？",py:"Nǐ chībǎo le ma?",m:{j:"ご飯食べた？（台湾式あいさつ）",e:"Have you eaten? (a common Taiwanese greeting)",k:"밥 먹었어요? (대만식 인사)"},note:{j:"本当に食事の心配をしているわけではなく「元気？」のニュアンス。",e:"It's small talk, like \"How are you?\" — not literally about food.",k:"실제 식사 걱정이 아니라 '잘 지내?' 정도의 인사."}},
]},
{icon:"🧋",t:"travel",cat:{j:"ドリンクスタンド・夜市",e:"Drink Stands & Night Markets",k:"음료 가게・야시장"},items:[
{z:"我要一杯珍珠奶茶。",py:"Wǒ yào yì bēi zhēnzhū nǎichá.",m:{j:"タピオカミルクティーを一杯ください。",e:"One bubble milk tea, please.",k:"버블 밀크티 한 잔 주세요."}},
{z:"半糖，少冰。",py:"Bàntáng, shǎobīng.",m:{j:"砂糖半分、氷少なめで。",e:"Half sugar, less ice.",k:"설탕 반, 얼음 적게요."},note:{j:"甘さ：正常糖→半糖→微糖→無糖。氷：正常冰→少冰→微冰→去冰。この2軸は台湾ドリンク注文の必修！",e:"Sugar: 正常→半→微→無; Ice: 正常→少→微→去. The two axes of every Taiwan drink order!",k:"당도: 正常→半→微→無, 얼음: 正常→少→微→去. 대만 음료 주문의 필수 개념!"}},
{z:"老闆，這個多少錢？",py:"Lǎobǎn, zhège duōshǎo qián?",m:{j:"すみません、これいくらですか。",e:"Boss, how much is this?",k:"사장님, 이거 얼마예요?"},note:{j:"店の人は男女問わず「老闆」「老闆娘」と呼ぶと親しみが出る。",e:"Calling the vendor 老闆 (boss) is friendly and very local.",k:"가게 주인을 \"老闆\"이라고 부르면 현지인 느낌."}},
{z:"可以內用嗎？",py:"Kěyǐ nèiyòng ma?",m:{j:"店内で食べられますか。",e:"Can I eat in?",k:"매장에서 먹을 수 있어요?"},note:{j:"内用＝イートイン、外帶＝テイクアウト。注文時に必ず聞かれる。",e:"內用 = eat in, 外帶 = take out. You'll be asked every time.",k:"內用 = 매장 식사, 外帶 = 포장. 주문할 때 꼭 묻는다."}},
{z:"外帶，謝謝。",py:"Wàidài, xièxie.",m:{j:"テイクアウトで、お願いします。",e:"Take out, please.",k:"포장이요, 감사합니다."}},
{z:"不要香菜。",py:"Bú yào xiāngcài.",m:{j:"パクチー抜きで。",e:"No cilantro, please.",k:"고수는 빼 주세요."}},
{z:"有一點辣嗎？",py:"Yǒu yìdiǎn là ma?",m:{j:"ちょっと辛いですか。",e:"Is it a bit spicy?",k:"조금 매워요?"}},
]},
{icon:"🍜",t:"travel",cat:{j:"レストラン",e:"At a Restaurant",k:"레스토랑"},items:[
{z:"請問幾位？——兩位。",py:"Qǐngwèn jǐ wèi? — Liǎng wèi.",m:{j:"何名様ですか。——2人です。",e:"How many? — Two.",k:"몇 분이세요? — 두 명이요."}},
{z:"請給我菜單。",py:"Qǐng gěi wǒ càidān.",m:{j:"メニューをください。",e:"The menu, please.",k:"메뉴판 주세요."}},
{z:"我要點餐。",py:"Wǒ yào diǎncān.",m:{j:"注文お願いします。",e:"I'd like to order.",k:"주문할게요."}},
{z:"招牌是什麼？",py:"Zhāopái shì shénme?",m:{j:"おすすめ（看板メニュー）は何ですか。",e:"What's your signature dish?",k:"대표 메뉴가 뭐예요?"}},
{z:"買單！／結帳！",py:"Mǎidān! / Jiézhàng!",m:{j:"お会計お願いします！",e:"Check, please!",k:"계산이요!"}},
{z:"可以刷卡嗎？",py:"Kěyǐ shuākǎ ma?",m:{j:"カードで払えますか。",e:"Can I pay by card?",k:"카드 돼요?"},note:{j:"夜市や小さい店は現金のみが多い。LINE Pay・悠遊付も普及中。",e:"Night markets and small shops are often cash only.",k:"야시장이나 작은 가게는 현금만 받는 곳이 많다."}},
]},
{icon:"🏨",t:"travel",cat:{j:"ホテル・宿泊",e:"Hotels & Lodging",k:"호텔・숙박"},items:[
{z:"我有訂房，這是我的護照。",py:"Wǒ yǒu dìngfáng, zhè shì wǒ de hùzhào.",m:{j:"予約しています。これがパスポートです。",e:"I have a reservation. Here's my passport.",k:"예약했습니다. 여기 여권이요."}},
{z:"幾點退房？",py:"Jǐ diǎn tuìfáng?",m:{j:"チェックアウトは何時ですか。",e:"What time is checkout?",k:"체크아웃은 몇 시예요?"}},
{z:"可以寄放行李嗎？",py:"Kěyǐ jìfàng xínglǐ ma?",m:{j:"荷物を預かってもらえますか。",e:"Can I leave my luggage here?",k:"짐을 맡길 수 있나요?"}},
{z:"有含早餐嗎？",py:"Yǒu hán zǎocān ma?",m:{j:"朝食は付いていますか。",e:"Is breakfast included?",k:"조식이 포함되어 있나요?"}},
{z:"冷氣好像壞了。",py:"Lěngqì hǎoxiàng huài le.",m:{j:"エアコンが壊れているみたいです。",e:"The AC seems to be broken.",k:"에어컨이 고장 난 것 같아요."}},
{z:"WiFi 密碼是多少？",py:"WiFi mìmǎ shì duōshǎo?",m:{j:"WiFiのパスワードは何ですか。",e:"What's the WiFi password?",k:"와이파이 비밀번호가 뭐예요?"}},
]},
{icon:"🚇",t:"both",cat:{j:"交通・移動",e:"Getting Around",k:"교통・이동"},items:[
{z:"我要去台北車站。",py:"Wǒ yào qù Táiběi chēzhàn.",m:{j:"台北駅へ行きたいです。",e:"I want to go to Taipei Main Station.",k:"타이베이역에 가려고 해요."}},
{z:"捷運站怎麼走？",py:"Jiéyùn zhàn zěnme zǒu?",m:{j:"MRTの駅へはどう行きますか。",e:"How do I get to the MRT station?",k:"MRT 역은 어떻게 가요?"}},
{z:"到了請告訴我。",py:"Dào le qǐng gàosù wǒ.",m:{j:"着いたら教えてください。",e:"Please tell me when we arrive.",k:"도착하면 알려 주세요."}},
{z:"我要加值一百塊。",py:"Wǒ yào jiāzhí yìbǎi kuài.",m:{j:"（悠遊カードに）100元チャージお願いします。",e:"I'd like to top up 100 NTD (EasyCard).",k:"(이지카드) 100위안 충전해 주세요."},note:{j:"悠遊卡（EasyCard）はコンビニでもチャージできる。",e:"You can top up an EasyCard at any convenience store.",k:"이지카드는 편의점에서도 충전 가능."}},
{z:"這班車去淡水嗎？",py:"Zhè bān chē qù Dànshuǐ ma?",m:{j:"この電車は淡水へ行きますか。",e:"Does this train go to Tamsui?",k:"이 차는 단수이에 가나요?"}},
]},
{icon:"🛍️",t:"travel",cat:{j:"買い物",e:"Shopping",k:"쇼핑"},items:[
{z:"我只是看看。",py:"Wǒ zhǐshì kànkan.",m:{j:"見ているだけです。",e:"I'm just looking.",k:"그냥 구경하는 거예요."}},
{z:"有別的顏色嗎？",py:"Yǒu bié de yánsè ma?",m:{j:"別の色はありますか。",e:"Do you have other colors?",k:"다른 색깔 있어요?"}},
{z:"可以便宜一點嗎？",py:"Kěyǐ piányí yìdiǎn ma?",m:{j:"少し安くしてもらえますか。",e:"Can you give me a discount?",k:"좀 깎아 주실 수 있어요?"}},
{z:"我要這個。",py:"Wǒ yào zhège.",m:{j:"これをください。",e:"I'll take this one.",k:"이걸로 할게요."}},
{z:"需要袋子嗎？——不用，謝謝。",py:"Xūyào dàizi ma? — Búyòng, xièxie.",m:{j:"袋は要りますか。——要りません、ありがとう。",e:"Need a bag? — No thanks.",k:"봉투 필요하세요? — 괜찮아요, 감사합니다."},note:{j:"台湾はレジ袋有料。断るときは「不要」より「不用」が柔らかい。",e:"Plastic bags cost extra in Taiwan. 不用 is the soft way to decline.",k:"대만은 비닐봉투가 유료. 거절할 때는 \"不用\"이 부드럽다."}},
]},
{icon:"🏠",t:"life",cat:{j:"部屋探し・大家さん",e:"Renting & Landlords",k:"집 구하기・집주인"},items:[
{z:"請問這間還有在租嗎？",py:"Qǐngwèn zhè jiān hái yǒu zài zū ma?",m:{j:"この部屋はまだ募集していますか。",e:"Is this room still available for rent?",k:"이 방 아직 임대 중인가요?"}},
{z:"房租含水電嗎？",py:"Fángzū hán shuǐdiàn ma?",m:{j:"家賃に水道・電気代は含まれますか。",e:"Does the rent include utilities?",k:"집세에 수도·전기 요금이 포함되나요?"},note:{j:"台湾の賃貸は「電費另計（電気代別）」が多い。夏の冷氣代に注意！",e:"Electricity is usually billed separately (電費另計). Watch out for summer AC bills!",k:"대만 월세는 전기요금 별도(電費另計)가 많다. 여름 에어컨 요금 주의!"}},
{z:"押金是兩個月嗎？",py:"Yājīn shì liǎng ge yuè ma?",m:{j:"敷金は2か月分ですか。",e:"Is the deposit two months' rent?",k:"보증금은 두 달치인가요?"}},
{z:"我想約看房。",py:"Wǒ xiǎng yuē kànfáng.",m:{j:"内見の予約をしたいです。",e:"I'd like to schedule a viewing.",k:"방을 보러 가고 싶은데 예약할게요."}},
{z:"熱水器壞了，可以請人來修嗎？",py:"Rèshuǐqì huài le, kěyǐ qǐng rén lái xiū ma?",m:{j:"給湯器が壊れたので、修理を呼んでもらえますか。",e:"The water heater is broken—can you send someone to fix it?",k:"온수기가 고장 났는데 수리 기사를 불러 주실 수 있나요?"}},
{z:"垃圾車幾點來？",py:"Lèsèchē jǐ diǎn lái?",m:{j:"ゴミ収集車は何時に来ますか。",e:"What time does the garbage truck come?",k:"쓰레기차는 몇 시에 와요?"},note:{j:"台湾は「エリーゼのために」を流すゴミ収集車に自分でゴミを持って行くスタイル。",e:"In Taiwan you bring your trash to the truck (the one playing Für Elise).",k:"대만은 '엘리제를 위하여'를 트는 수거차에 직접 쓰레기를 갖다 버린다."}},
]},
{icon:"🏥",t:"life",cat:{j:"病院・薬局",e:"Clinics & Pharmacies",k:"병원・약국"},items:[
{z:"我要掛號，初診。",py:"Wǒ yào guàhào, chūzhěn.",m:{j:"受付お願いします。初診です。",e:"I'd like to register—first visit.",k:"접수할게요. 초진입니다."}},
{z:"我有健保卡。",py:"Wǒ yǒu jiànbǎokǎ.",m:{j:"健保カードを持っています。",e:"I have an NHI card.",k:"건강보험증 있습니다."},note:{j:"台湾の健保は外国人も加入OK（居留証取得後6か月など条件あり）。診察が数百元で済む神制度。",e:"Foreign residents can join Taiwan's NHI. Visits often cost just a few hundred NTD.",k:"외국인도 대만 건보 가입 가능. 진료비가 몇백 위안이면 되는 좋은 제도."}},
{z:"我從昨天開始發燒。",py:"Wǒ cóng zuótiān kāishǐ fāshāo.",m:{j:"昨日から熱があります。",e:"I've had a fever since yesterday.",k:"어제부터 열이 나요."}},
{z:"我對海鮮過敏。",py:"Wǒ duì hǎixiān guòmǐn.",m:{j:"海鮮アレルギーがあります。",e:"I'm allergic to seafood.",k:"해산물 알레르기가 있어요."}},
{z:"這個藥飯後吃嗎？",py:"Zhège yào fànhòu chī ma?",m:{j:"この薬は食後に飲みますか。",e:"Do I take this medicine after meals?",k:"이 약은 식후에 먹나요?"}},
{z:"附近有藥局嗎？",py:"Fùjìn yǒu yàojú ma?",m:{j:"近くに薬局はありますか。",e:"Is there a pharmacy nearby?",k:"근처에 약국이 있나요?"}},
]},
{icon:"🏦",t:"life",cat:{j:"銀行・携帯・手続き",e:"Banking, Phones & Paperwork",k:"은행・휴대폰・수속"},items:[
{z:"我想開戶。",py:"Wǒ xiǎng kāihù.",m:{j:"口座を開設したいです。",e:"I'd like to open an account.",k:"계좌를 개설하고 싶습니다."},note:{j:"必要なもの：居留證＋パスポート＋印鑑（台湾は今も印鑑社会！）。",e:"Bring your ARC, passport, and a personal seal — Taiwan still loves seals!",k:"거류증+여권+도장 필요. 대만은 아직도 도장 사회!"}},
{z:"我要辦手機門號。",py:"Wǒ yào bàn shǒujī ménhào.",m:{j:"携帯の番号契約をしたいです。",e:"I'd like to sign up for a mobile plan.",k:"휴대폰 번호를 개통하고 싶어요."}},
{z:"這是我的居留證。",py:"Zhè shì wǒ de jūliúzhèng.",m:{j:"これが私の居留証（ARC）です。",e:"This is my ARC (residence permit).",k:"이것이 제 거류증(ARC)입니다."}},
{z:"請問要填哪些資料？",py:"Qǐngwèn yào tián nǎxiē zīliào?",m:{j:"どの書類に記入すればいいですか。",e:"Which forms do I need to fill out?",k:"어떤 서류를 작성해야 하나요?"}},
{z:"可以幫我叫外送嗎？",py:"Kěyǐ bāng wǒ jiào wàisòng ma?",m:{j:"デリバリーを頼んでもらえますか。",e:"Can you order delivery for me?",k:"배달 좀 시켜 줄 수 있어요?"},note:{j:"foodpanda と Uber Eats が二大勢力。「外送」=デリバリー。",e:"foodpanda and Uber Eats dominate. 外送 = delivery.",k:"푸드판다와 우버이츠가 양대 산맥. 外送 = 배달."}},
]},
{icon:"💼",t:"life",cat:{j:"職場",e:"At Work",k:"직장"},items:[
{z:"不好意思，我想請假一天。",py:"Bù hǎoyìsi, wǒ xiǎng qǐngjià yì tiān.",m:{j:"すみません、1日休みを取りたいのですが。",e:"Excuse me, I'd like to take a day off.",k:"죄송한데 하루 휴가를 내고 싶습니다."}},
{z:"這個案子進度到哪了？",py:"Zhège ànzi jìndù dào nǎ le?",m:{j:"この案件の進捗はどこまで進んでいますか。",e:"Where are we on this project?",k:"이 프로젝트 진행 상황이 어떻게 되나요?"}},
{z:"我下午要開會，晚點回你。",py:"Wǒ xiàwǔ yào kāihuì, wǎndiǎn huí nǐ.",m:{j:"午後は会議なので、後で返事します。",e:"I have a meeting this afternoon—I'll get back to you later.",k:"오후에 회의가 있어서 나중에 답할게요."}},
{z:"辛苦了！",py:"Xīnkǔ le!",m:{j:"お疲れさま！",e:"Thanks for your hard work!",k:"수고하셨습니다!"},note:{j:"日本語の「お疲れさま」とほぼ同じ感覚で毎日使える。",e:"Works almost exactly like Japanese otsukaresama.",k:"일본어 '오츠카레사마'와 거의 같은 느낌."}},
{z:"麻煩你了，感謝！",py:"Máfán nǐ le, gǎnxiè!",m:{j:"お手数おかけします、ありがとうございます！",e:"Sorry to trouble you—thanks!",k:"번거롭게 해서 죄송해요, 감사합니다!"}},
{z:"我先下班囉，明天見！",py:"Wǒ xiān xiàbān lo, míngtiān jiàn!",m:{j:"お先に失礼します、また明日！",e:"I'm heading out—see you tomorrow!",k:"먼저 퇴근할게요, 내일 봐요!"}},
]},
{icon:"🆘",t:"both",cat:{j:"困ったとき・緊急",e:"Trouble & Emergencies",k:"곤란할 때・긴급"},items:[
{z:"不好意思，請問一下。",py:"Bù hǎoyìsi, qǐngwèn yíxià.",m:{j:"すみません、ちょっとお尋ねします。",e:"Excuse me, may I ask something?",k:"실례합니다, 뭐 좀 여쭤볼게요."},note:{j:"「不好意思」は台湾会話の万能クッション言葉。1日10回は聞く。",e:"不好意思 is Taiwan's all-purpose softener — you'll hear it 10 times a day.",k:"\"不好意思\"는 대만 회화의 만능 쿠션어."}},
{z:"我聽不懂。",py:"Wǒ tīng bù dǒng.",m:{j:"（聞いて）分かりません。",e:"I don't understand.",k:"못 알아듣겠어요."}},
{z:"請說慢一點。",py:"Qǐng shuō màn yìdiǎn.",m:{j:"ゆっくり話してください。",e:"Please speak slowly.",k:"천천히 말해 주세요."}},
{z:"可以用英文嗎？",py:"Kěyǐ yòng Yīngwén ma?",m:{j:"英語でもいいですか。",e:"Can we use English?",k:"영어로 해도 돼요?"}},
{z:"我的錢包不見了！",py:"Wǒ de qiánbāo bújiàn le!",m:{j:"財布がなくなりました！",e:"My wallet is gone!",k:"지갑이 없어졌어요!"}},
{z:"請幫我叫警察。",py:"Qǐng bāng wǒ jiào jǐngchá.",m:{j:"警察を呼んでください。",e:"Please call the police.",k:"경찰을 불러 주세요."},note:{j:"緊急番号：警察110・消防/救急119。日本と同じで覚えやすい。",e:"Emergency numbers: police 110, fire/ambulance 119 — same as Japan.",k:"긴급 번호: 경찰 110, 소방/구급 119."}},
{z:"我迷路了，這裡是哪裡？",py:"Wǒ mílù le, zhèlǐ shì nǎlǐ?",m:{j:"道に迷いました。ここはどこですか。",e:"I'm lost—where am I?",k:"길을 잃었어요. 여기가 어디예요?"}},
{z:"沒問題！",py:"Méi wèntí!",m:{j:"問題ないよ！",e:"No problem!",k:"문제없어요!"}},
]},
];
if (typeof module !== "undefined") module.exports = { PHRASES_L1 };
