// StayTW Study — TOCFL Level 1 (入門) 単語
// 形式: w=繁體字, py=拼音, zy=注音, c=品詞, m=訳(j/e/k), ex=例文(z/py/j/e/k)
const VOCAB_L1 = [
// ── 人・呼び方 ──
{w:"我",py:"wǒ",zy:"ㄨㄛˇ",c:"代",m:{j:"私・僕",e:"I; me",k:"나, 저"},ex:{z:"我是日本人。",py:"Wǒ shì Rìběnrén.",j:"私は日本人です。",e:"I am Japanese.",k:"저는 일본인입니다."}},
{w:"你",py:"nǐ",zy:"ㄋㄧˇ",c:"代",m:{j:"あなた・君",e:"you",k:"너, 당신"},ex:{z:"你是學生嗎？",py:"Nǐ shì xuéshēng ma?",j:"あなたは学生ですか。",e:"Are you a student?",k:"당신은 학생입니까?"}},
{w:"您",py:"nín",zy:"ㄋㄧㄣˊ",c:"代",m:{j:"あなた（敬称）",e:"you (polite)",k:"당신 (높임)"},ex:{z:"您好，請問您貴姓？",py:"Nín hǎo, qǐngwèn nín guìxìng?",j:"こんにちは、お名前（姓）を伺えますか。",e:"Hello, may I ask your surname?",k:"안녕하세요, 성함이 어떻게 되세요?"}},
{w:"他",py:"tā",zy:"ㄊㄚ",c:"代",m:{j:"彼",e:"he; him",k:"그"},ex:{z:"他是我的朋友。",py:"Tā shì wǒ de péngyǒu.",j:"彼は私の友達です。",e:"He is my friend.",k:"그는 제 친구입니다."}},
{w:"她",py:"tā",zy:"ㄊㄚ",c:"代",m:{j:"彼女",e:"she; her",k:"그녀"},ex:{z:"她是台灣人。",py:"Tā shì Táiwānrén.",j:"彼女は台湾人です。",e:"She is Taiwanese.",k:"그녀는 대만 사람입니다."}},
{w:"我們",py:"wǒmen",zy:"ㄨㄛˇ ˙ㄇㄣ",c:"代",m:{j:"私たち",e:"we; us",k:"우리"},ex:{z:"我們一起去夜市。",py:"Wǒmen yìqǐ qù yèshì.",j:"私たちは一緒に夜市へ行きます。",e:"We go to the night market together.",k:"우리는 같이 야시장에 갑니다."}},
{w:"大家",py:"dàjiā",zy:"ㄉㄚˋ ㄐㄧㄚ",c:"代",m:{j:"みんな・皆さん",e:"everyone",k:"모두, 여러분"},ex:{z:"大家好！",py:"Dàjiā hǎo!",j:"皆さん、こんにちは！",e:"Hello, everyone!",k:"여러분, 안녕하세요!"}},
{w:"人",py:"rén",zy:"ㄖㄣˊ",c:"名",m:{j:"人",e:"person; people",k:"사람"},ex:{z:"夜市有很多人。",py:"Yèshì yǒu hěn duō rén.",j:"夜市には人がたくさんいます。",e:"There are many people at the night market.",k:"야시장에는 사람이 많습니다."}},
{w:"朋友",py:"péngyǒu",zy:"ㄆㄥˊ ㄧㄡˇ",c:"名",m:{j:"友達",e:"friend",k:"친구"},ex:{z:"我跟朋友去吃飯。",py:"Wǒ gēn péngyǒu qù chīfàn.",j:"友達とご飯を食べに行きます。",e:"I go eat with my friend.",k:"친구와 밥을 먹으러 갑니다."}},
{w:"名字",py:"míngzi",zy:"ㄇㄧㄥˊ ˙ㄗ",c:"名",m:{j:"名前",e:"name",k:"이름"},ex:{z:"你叫什麼名字？",py:"Nǐ jiào shénme míngzi?",j:"お名前は何ですか。",e:"What is your name?",k:"이름이 뭐예요?"}},
{w:"先生",py:"xiānshēng",zy:"ㄒㄧㄢ ㄕㄥ",c:"名",m:{j:"〜さん（男性）・ご主人",e:"Mr.; husband",k:"~씨 (남성), 남편"},ex:{z:"田中先生是日本人。",py:"Tiánzhōng xiānshēng shì Rìběnrén.",j:"田中さんは日本人です。",e:"Mr. Tanaka is Japanese.",k:"다나카 씨는 일본인입니다."}},
{w:"小姐",py:"xiǎojiě",zy:"ㄒㄧㄠˇ ㄐㄧㄝˇ",c:"名",m:{j:"〜さん（女性）",e:"Miss; Ms.",k:"~씨 (여성), 아가씨"},ex:{z:"林小姐在銀行工作。",py:"Lín xiǎojiě zài yínháng gōngzuò.",j:"林さんは銀行で働いています。",e:"Miss Lin works at a bank.",k:"린 씨는 은행에서 일합니다."}},
// ── 家族 ──
{w:"家人",py:"jiārén",zy:"ㄐㄧㄚ ㄖㄣˊ",c:"名",m:{j:"家族",e:"family (members)",k:"가족"},ex:{z:"我家有四個人。",py:"Wǒ jiā yǒu sì ge rén.",j:"うちは4人家族です。",e:"My family has four people.",k:"우리 가족은 네 명입니다."}},
{w:"爸爸",py:"bàba",zy:"ㄅㄚˋ ˙ㄅㄚ",c:"名",m:{j:"お父さん",e:"dad; father",k:"아빠"},ex:{z:"我爸爸每天工作。",py:"Wǒ bàba měitiān gōngzuò.",j:"父は毎日働いています。",e:"My dad works every day.",k:"아빠는 매일 일합니다."}},
{w:"媽媽",py:"māma",zy:"ㄇㄚ ˙ㄇㄚ",c:"名",m:{j:"お母さん",e:"mom; mother",k:"엄마"},ex:{z:"媽媽做的菜很好吃。",py:"Māma zuò de cài hěn hǎochī.",j:"母の作る料理はとてもおいしいです。",e:"The food my mom makes is delicious.",k:"엄마가 만든 요리는 아주 맛있습니다."}},
{w:"哥哥",py:"gēge",zy:"ㄍㄜ ˙ㄍㄜ",c:"名",m:{j:"お兄さん",e:"older brother",k:"형, 오빠"},ex:{z:"我哥哥住在台北。",py:"Wǒ gēge zhù zài Táiběi.",j:"兄は台北に住んでいます。",e:"My older brother lives in Taipei.",k:"형(오빠)은 타이베이에 삽니다."}},
{w:"姊姊",py:"jiějie",zy:"ㄐㄧㄝˇ ˙ㄐㄧㄝ",c:"名",m:{j:"お姉さん",e:"older sister",k:"누나, 언니"},ex:{z:"姊姊很喜歡喝咖啡。",py:"Jiějie hěn xǐhuān hē kāfēi.",j:"姉はコーヒーが大好きです。",e:"My older sister loves coffee.",k:"누나(언니)는 커피를 아주 좋아합니다."}},
{w:"弟弟",py:"dìdi",zy:"ㄉㄧˋ ˙ㄉㄧ",c:"名",m:{j:"弟",e:"younger brother",k:"남동생"},ex:{z:"我弟弟今年十歲。",py:"Wǒ dìdi jīnnián shí suì.",j:"弟は今年10歳です。",e:"My younger brother is ten this year.",k:"남동생은 올해 열 살입니다."}},
{w:"妹妹",py:"mèimei",zy:"ㄇㄟˋ ˙ㄇㄟ",c:"名",m:{j:"妹",e:"younger sister",k:"여동생"},ex:{z:"妹妹在學日文。",py:"Mèimei zài xué Rìwén.",j:"妹は日本語を勉強しています。",e:"My younger sister is learning Japanese.",k:"여동생은 일본어를 배우고 있습니다."}},
// ── 職業・身分 ──
{w:"老師",py:"lǎoshī",zy:"ㄌㄠˇ ㄕ",c:"名",m:{j:"先生・教師",e:"teacher",k:"선생님"},ex:{z:"王老師教中文。",py:"Wáng lǎoshī jiāo Zhōngwén.",j:"王先生は中国語を教えています。",e:"Teacher Wang teaches Chinese.",k:"왕 선생님은 중국어를 가르칩니다."}},
{w:"學生",py:"xuéshēng",zy:"ㄒㄩㄝˊ ㄕㄥ",c:"名",m:{j:"学生",e:"student",k:"학생"},ex:{z:"我是大學生。",py:"Wǒ shì dàxuéshēng.",j:"私は大学生です。",e:"I am a university student.",k:"저는 대학생입니다."}},
{w:"醫生",py:"yīshēng",zy:"ㄧ ㄕㄥ",c:"名",m:{j:"医者",e:"doctor",k:"의사"},ex:{z:"他是醫院的醫生。",py:"Tā shì yīyuàn de yīshēng.",j:"彼は病院の医者です。",e:"He is a doctor at the hospital.",k:"그는 병원 의사입니다."}},
{w:"工程師",py:"gōngchéngshī",zy:"ㄍㄨㄥ ㄔㄥˊ ㄕ",c:"名",m:{j:"エンジニア",e:"engineer",k:"엔지니어"},ex:{z:"我是前端工程師。",py:"Wǒ shì qiánduān gōngchéngshī.",j:"私はフロントエンドエンジニアです。",e:"I am a front-end engineer.",k:"저는 프런트엔드 엔지니어입니다."}},
// ── 場所・地名 ──
{w:"台灣",py:"Táiwān",zy:"ㄊㄞˊ ㄨㄢ",c:"名",m:{j:"台湾",e:"Taiwan",k:"대만"},ex:{z:"我很喜歡台灣。",py:"Wǒ hěn xǐhuān Táiwān.",j:"私は台湾が大好きです。",e:"I really like Taiwan.",k:"저는 대만을 아주 좋아합니다."}},
{w:"日本",py:"Rìběn",zy:"ㄖˋ ㄅㄣˇ",c:"名",m:{j:"日本",e:"Japan",k:"일본"},ex:{z:"我從日本來。",py:"Wǒ cóng Rìběn lái.",j:"私は日本から来ました。",e:"I come from Japan.",k:"저는 일본에서 왔습니다."}},
{w:"台北",py:"Táiběi",zy:"ㄊㄞˊ ㄅㄟˇ",c:"名",m:{j:"台北",e:"Taipei",k:"타이베이"},ex:{z:"台北一〇一很高。",py:"Táiběi yī líng yī hěn gāo.",j:"台北101はとても高いです。",e:"Taipei 101 is very tall.",k:"타이베이 101은 아주 높습니다."}},
{w:"家",py:"jiā",zy:"ㄐㄧㄚ",c:"名",m:{j:"家・うち",e:"home; house",k:"집"},ex:{z:"我想回家。",py:"Wǒ xiǎng huí jiā.",j:"家に帰りたいです。",e:"I want to go home.",k:"집에 가고 싶습니다."}},
{w:"學校",py:"xuéxiào",zy:"ㄒㄩㄝˊ ㄒㄧㄠˋ",c:"名",m:{j:"学校",e:"school",k:"학교"},ex:{z:"學校在捷運站旁邊。",py:"Xuéxiào zài jiéyùn zhàn pángbiān.",j:"学校はMRTの駅のそばにあります。",e:"The school is next to the MRT station.",k:"학교는 지하철역 옆에 있습니다."}},
{w:"公司",py:"gōngsī",zy:"ㄍㄨㄥ ㄙ",c:"名",m:{j:"会社",e:"company",k:"회사"},ex:{z:"我在台北的公司上班。",py:"Wǒ zài Táiběi de gōngsī shàngbān.",j:"私は台北の会社に勤めています。",e:"I work at a company in Taipei.",k:"저는 타이베이에 있는 회사에 다닙니다."}},
{w:"醫院",py:"yīyuàn",zy:"ㄧ ㄩㄢˋ",c:"名",m:{j:"病院",e:"hospital",k:"병원"},ex:{z:"醫院在銀行對面。",py:"Yīyuàn zài yínháng duìmiàn.",j:"病院は銀行の向かいにあります。",e:"The hospital is across from the bank.",k:"병원은 은행 맞은편에 있습니다."}},
{w:"銀行",py:"yínháng",zy:"ㄧㄣˊ ㄏㄤˊ",c:"名",m:{j:"銀行",e:"bank",k:"은행"},ex:{z:"銀行幾點開門？",py:"Yínháng jǐ diǎn kāimén?",j:"銀行は何時に開きますか。",e:"What time does the bank open?",k:"은행은 몇 시에 문을 엽니까?"}},
{w:"餐廳",py:"cāntīng",zy:"ㄘㄢ ㄊㄧㄥ",c:"名",m:{j:"レストラン",e:"restaurant",k:"레스토랑, 식당"},ex:{z:"這家餐廳很有名。",py:"Zhè jiā cāntīng hěn yǒumíng.",j:"このレストランはとても有名です。",e:"This restaurant is very famous.",k:"이 식당은 아주 유명합니다."}},
{w:"夜市",py:"yèshì",zy:"ㄧㄝˋ ㄕˋ",c:"名",m:{j:"夜市（ナイトマーケット）",e:"night market",k:"야시장"},ex:{z:"晚上我們去夜市吃小吃。",py:"Wǎnshàng wǒmen qù yèshì chī xiǎochī.",j:"夜は夜市へ屋台グルメを食べに行きます。",e:"In the evening we go to the night market for snacks.",k:"저녁에 우리는 야시장에 가서 간식을 먹습니다."}},
{w:"便利商店",py:"biànlì shāngdiàn",zy:"ㄅㄧㄢˋ ㄌㄧˋ ㄕㄤ ㄉㄧㄢˋ",c:"名",m:{j:"コンビニ",e:"convenience store",k:"편의점"},ex:{z:"便利商店二十四小時都開。",py:"Biànlì shāngdiàn èrshísì xiǎoshí dōu kāi.",j:"コンビニは24時間開いています。",e:"Convenience stores are open 24 hours.",k:"편의점은 24시간 영업합니다."}},
{w:"廁所",py:"cèsuǒ",zy:"ㄘㄜˋ ㄙㄨㄛˇ",c:"名",m:{j:"トイレ",e:"toilet; restroom",k:"화장실"},ex:{z:"請問廁所在哪裡？",py:"Qǐngwèn cèsuǒ zài nǎlǐ?",j:"すみません、トイレはどこですか。",e:"Excuse me, where is the restroom?",k:"실례합니다, 화장실은 어디에 있습니까?"}},
// ── 交通 ──
{w:"捷運",py:"jiéyùn",zy:"ㄐㄧㄝˊ ㄩㄣˋ",c:"名",m:{j:"MRT（台湾の地下鉄）",e:"MRT (Taipei metro)",k:"MRT (대만 지하철)"},ex:{z:"我每天坐捷運上班。",py:"Wǒ měitiān zuò jiéyùn shàngbān.",j:"毎日MRTで通勤しています。",e:"I take the MRT to work every day.",k:"저는 매일 MRT를 타고 출근합니다."}},
{w:"公車",py:"gōngchē",zy:"ㄍㄨㄥ ㄔㄜ",c:"名",m:{j:"バス（路線バス）",e:"(city) bus",k:"버스"},ex:{z:"這班公車去台北車站嗎？",py:"Zhè bān gōngchē qù Táiběi chēzhàn ma?",j:"このバスは台北駅へ行きますか。",e:"Does this bus go to Taipei Main Station?",k:"이 버스는 타이베이역에 갑니까?"}},
{w:"火車",py:"huǒchē",zy:"ㄏㄨㄛˇ ㄔㄜ",c:"名",m:{j:"電車・汽車（台鉄）",e:"train",k:"기차"},ex:{z:"我們坐火車去花蓮。",py:"Wǒmen zuò huǒchē qù Huālián.",j:"私たちは電車で花蓮へ行きます。",e:"We take the train to Hualien.",k:"우리는 기차를 타고 화롄에 갑니다."}},
{w:"高鐵",py:"gāotiě",zy:"ㄍㄠ ㄊㄧㄝˇ",c:"名",m:{j:"台湾新幹線（高速鉄道）",e:"HSR (high-speed rail)",k:"고속철도 (THSR)"},ex:{z:"坐高鐵到高雄要兩個小時。",py:"Zuò gāotiě dào Gāoxióng yào liǎng ge xiǎoshí.",j:"高鉄で高雄まで2時間かかります。",e:"It takes two hours to Kaohsiung by HSR.",k:"고속철도로 가오슝까지 두 시간 걸립니다."}},
{w:"機車",py:"jīchē",zy:"ㄐㄧ ㄔㄜ",c:"名",m:{j:"バイク・スクーター",e:"scooter; motorbike",k:"오토바이, 스쿠터"},ex:{z:"台灣的機車很多。",py:"Táiwān de jīchē hěn duō.",j:"台湾はバイクがとても多いです。",e:"There are many scooters in Taiwan.",k:"대만에는 오토바이가 아주 많습니다."}},
{w:"計程車",py:"jìchéngchē",zy:"ㄐㄧˋ ㄔㄥˊ ㄔㄜ",c:"名",m:{j:"タクシー",e:"taxi",k:"택시"},ex:{z:"我們坐計程車去機場吧。",py:"Wǒmen zuò jìchéngchē qù jīchǎng ba.",j:"タクシーで空港へ行きましょう。",e:"Let's take a taxi to the airport.",k:"택시를 타고 공항에 갑시다."}},
{w:"車站",py:"chēzhàn",zy:"ㄔㄜ ㄓㄢˋ",c:"名",m:{j:"駅・バス停",e:"station; stop",k:"역, 정류장"},ex:{z:"車站離這裡很近。",py:"Chēzhàn lí zhèlǐ hěn jìn.",j:"駅はここからとても近いです。",e:"The station is very close to here.",k:"역은 여기서 아주 가깝습니다."}},
{w:"機場",py:"jīchǎng",zy:"ㄐㄧ ㄔㄤˇ",c:"名",m:{j:"空港",e:"airport",k:"공항"},ex:{z:"桃園機場很大。",py:"Táoyuán jīchǎng hěn dà.",j:"桃園空港はとても大きいです。",e:"Taoyuan Airport is very big.",k:"타오위안 공항은 아주 큽니다."}},
// ── 食べ物・飲み物 ──
{w:"水",py:"shuǐ",zy:"ㄕㄨㄟˇ",c:"名",m:{j:"水",e:"water",k:"물"},ex:{z:"請給我一杯水。",py:"Qǐng gěi wǒ yì bēi shuǐ.",j:"お水を一杯ください。",e:"Please give me a glass of water.",k:"물 한 잔 주세요."}},
{w:"茶",py:"chá",zy:"ㄔㄚˊ",c:"名",m:{j:"お茶",e:"tea",k:"차"},ex:{z:"台灣的茶很有名。",py:"Táiwān de chá hěn yǒumíng.",j:"台湾のお茶はとても有名です。",e:"Taiwanese tea is very famous.",k:"대만 차는 아주 유명합니다."}},
{w:"咖啡",py:"kāfēi",zy:"ㄎㄚ ㄈㄟ",c:"名",m:{j:"コーヒー",e:"coffee",k:"커피"},ex:{z:"我每天早上喝咖啡。",py:"Wǒ měitiān zǎoshang hē kāfēi.",j:"毎朝コーヒーを飲みます。",e:"I drink coffee every morning.",k:"저는 매일 아침 커피를 마십니다."}},
{w:"珍珠奶茶",py:"zhēnzhū nǎichá",zy:"ㄓㄣ ㄓㄨ ㄋㄞˇ ㄔㄚˊ",c:"名",m:{j:"タピオカミルクティー",e:"bubble milk tea",k:"버블 밀크티"},ex:{z:"我要一杯珍珠奶茶，半糖少冰。",py:"Wǒ yào yì bēi zhēnzhū nǎichá, bàntáng shǎobīng.",j:"タピオカミルクティーを一杯、砂糖半分・氷少なめで。",e:"One bubble tea, half sugar, less ice.",k:"버블 밀크티 한 잔 주세요, 설탕 반, 얼음 적게요."}},
{w:"啤酒",py:"píjiǔ",zy:"ㄆㄧˊ ㄐㄧㄡˇ",c:"名",m:{j:"ビール",e:"beer",k:"맥주"},ex:{z:"來兩瓶台灣啤酒。",py:"Lái liǎng píng Táiwān píjiǔ.",j:"台湾ビールを2本ください。",e:"Two bottles of Taiwan Beer, please.",k:"대만 맥주 두 병 주세요."}},
{w:"飯",py:"fàn",zy:"ㄈㄢˋ",c:"名",m:{j:"ご飯・食事",e:"rice; meal",k:"밥, 식사"},ex:{z:"你吃飯了嗎？",py:"Nǐ chīfàn le ma?",j:"ご飯を食べましたか。（あいさつにもなる）",e:"Have you eaten?",k:"밥 먹었어요?"}},
{w:"麵",py:"miàn",zy:"ㄇㄧㄢˋ",c:"名",m:{j:"麺・そば",e:"noodles",k:"면, 국수"},ex:{z:"牛肉麵是台灣名菜。",py:"Niúròumiàn shì Táiwān míngcài.",j:"牛肉麺は台湾の名物料理です。",e:"Beef noodles are a famous Taiwanese dish.",k:"우육면은 대만의 유명한 요리입니다."}},
{w:"小籠包",py:"xiǎolóngbāo",zy:"ㄒㄧㄠˇ ㄌㄨㄥˊ ㄅㄠ",c:"名",m:{j:"小籠包（ショーロンポー）",e:"soup dumplings",k:"샤오룽바오"},ex:{z:"我們點一籠小籠包吧。",py:"Wǒmen diǎn yì lóng xiǎolóngbāo ba.",j:"小籠包を一せいろ頼みましょう。",e:"Let's order a basket of soup dumplings.",k:"샤오룽바오 한 판 시킵시다."}},
{w:"滷肉飯",py:"lǔròufàn",zy:"ㄌㄨˇ ㄖㄡˋ ㄈㄢˋ",c:"名",m:{j:"ルーローハン（豚そぼろかけご飯）",e:"braised pork rice",k:"루러우판"},ex:{z:"老闆，一碗滷肉飯。",py:"Lǎobǎn, yì wǎn lǔròufàn.",j:"すみません、ルーローハンを一杯。",e:"Boss, one bowl of braised pork rice.",k:"사장님, 루러우판 한 그릇이요."}},
{w:"水果",py:"shuǐguǒ",zy:"ㄕㄨㄟˇ ㄍㄨㄛˇ",c:"名",m:{j:"果物",e:"fruit",k:"과일"},ex:{z:"台灣的水果又便宜又好吃。",py:"Táiwān de shuǐguǒ yòu piányí yòu hǎochī.",j:"台湾の果物は安くておいしいです。",e:"Taiwanese fruit is cheap and delicious.",k:"대만 과일은 싸고 맛있습니다."}},
{w:"芒果",py:"mángguǒ",zy:"ㄇㄤˊ ㄍㄨㄛˇ",c:"名",m:{j:"マンゴー",e:"mango",k:"망고"},ex:{z:"夏天要吃芒果冰！",py:"Xiàtiān yào chī mángguǒ bīng!",j:"夏はマンゴーかき氷を食べなきゃ！",e:"In summer you have to eat mango shaved ice!",k:"여름에는 망고 빙수를 먹어야죠!"}},
{w:"早餐",py:"zǎocān",zy:"ㄗㄠˇ ㄘㄢ",c:"名",m:{j:"朝ご飯",e:"breakfast",k:"아침 식사"},ex:{z:"台灣人常在早餐店買早餐。",py:"Táiwānrén cháng zài zǎocāndiàn mǎi zǎocān.",j:"台湾人はよく朝食店で朝ご飯を買います。",e:"Taiwanese often buy breakfast at breakfast shops.",k:"대만 사람들은 흔히 아침 가게에서 아침을 삽니다."}},
{w:"晚餐",py:"wǎncān",zy:"ㄨㄢˇ ㄘㄢ",c:"名",m:{j:"晩ご飯",e:"dinner",k:"저녁 식사"},ex:{z:"今天晚餐想吃什麼？",py:"Jīntiān wǎncān xiǎng chī shénme?",j:"今日の晩ご飯は何が食べたい？",e:"What do you want for dinner tonight?",k:"오늘 저녁에 뭐 먹고 싶어요?"}},
// ── 時間 ──
{w:"今天",py:"jīntiān",zy:"ㄐㄧㄣ ㄊㄧㄢ",c:"名",m:{j:"今日",e:"today",k:"오늘"},ex:{z:"今天天氣很好。",py:"Jīntiān tiānqì hěn hǎo.",j:"今日は天気がいいです。",e:"The weather is nice today.",k:"오늘은 날씨가 좋습니다."}},
{w:"明天",py:"míngtiān",zy:"ㄇㄧㄥˊ ㄊㄧㄢ",c:"名",m:{j:"明日",e:"tomorrow",k:"내일"},ex:{z:"明天見！",py:"Míngtiān jiàn!",j:"また明日！",e:"See you tomorrow!",k:"내일 봐요!"}},
{w:"昨天",py:"zuótiān",zy:"ㄗㄨㄛˊ ㄊㄧㄢ",c:"名",m:{j:"昨日",e:"yesterday",k:"어제"},ex:{z:"我昨天去了故宮。",py:"Wǒ zuótiān qù le Gùgōng.",j:"昨日、故宮博物院へ行きました。",e:"I went to the Palace Museum yesterday.",k:"저는 어제 고궁 박물관에 갔습니다."}},
{w:"現在",py:"xiànzài",zy:"ㄒㄧㄢˋ ㄗㄞˋ",c:"名",m:{j:"今",e:"now",k:"지금"},ex:{z:"現在幾點？",py:"Xiànzài jǐ diǎn?",j:"今、何時ですか。",e:"What time is it now?",k:"지금 몇 시예요?"}},
{w:"早上",py:"zǎoshang",zy:"ㄗㄠˇ ˙ㄕㄤ",c:"名",m:{j:"朝",e:"morning",k:"아침"},ex:{z:"我早上七點起床。",py:"Wǒ zǎoshang qī diǎn qǐchuáng.",j:"朝7時に起きます。",e:"I get up at seven in the morning.",k:"저는 아침 7시에 일어납니다."}},
{w:"晚上",py:"wǎnshàng",zy:"ㄨㄢˇ ˙ㄕㄤ",c:"名",m:{j:"夜・晩",e:"evening; night",k:"저녁, 밤"},ex:{z:"晚上一起去夜市，好嗎？",py:"Wǎnshàng yìqǐ qù yèshì, hǎo ma?",j:"夜、一緒に夜市へ行きませんか。",e:"Shall we go to the night market tonight?",k:"저녁에 같이 야시장에 갈까요?"}},
{w:"星期",py:"xīngqí",zy:"ㄒㄧㄥ ㄑㄧˊ",c:"名",m:{j:"週・曜日（台湾では xīngqí）",e:"week",k:"주, 요일"},ex:{z:"星期六你有空嗎？",py:"Xīngqíliù nǐ yǒu kòng ma?",j:"土曜日、空いていますか。",e:"Are you free on Saturday?",k:"토요일에 시간 있어요?"}},
{w:"時間",py:"shíjiān",zy:"ㄕˊ ㄐㄧㄢ",c:"名",m:{j:"時間",e:"time",k:"시간"},ex:{z:"我今天沒有時間。",py:"Wǒ jīntiān méiyǒu shíjiān.",j:"今日は時間がありません。",e:"I don't have time today.",k:"저는 오늘 시간이 없습니다."}},
{w:"點",py:"diǎn",zy:"ㄉㄧㄢˇ",c:"量",m:{j:"〜時",e:"o'clock",k:"~시"},ex:{z:"我們三點在車站見。",py:"Wǒmen sān diǎn zài chēzhàn jiàn.",j:"3時に駅で会いましょう。",e:"Let's meet at the station at three.",k:"3시에 역에서 만납시다."}},
// ── 数・お金 ──
{w:"一",py:"yī",zy:"ㄧ",c:"數",m:{j:"一",e:"one",k:"일, 하나"},ex:{z:"我要一杯咖啡。",py:"Wǒ yào yì bēi kāfēi.",j:"コーヒーを一杯ください。",e:"I'd like one coffee.",k:"커피 한 잔 주세요."}},
{w:"兩",py:"liǎng",zy:"ㄌㄧㄤˇ",c:"數",m:{j:"二つの（量詞の前では二→兩）",e:"two (before measure words)",k:"둘 (양사 앞)"},ex:{z:"我有兩個妹妹。",py:"Wǒ yǒu liǎng ge mèimei.",j:"妹が2人います。",e:"I have two younger sisters.",k:"여동생이 두 명 있습니다."}},
{w:"三",py:"sān",zy:"ㄙㄢ",c:"數",m:{j:"三",e:"three",k:"삼, 셋"},ex:{z:"我學中文三個月了。",py:"Wǒ xué Zhōngwén sān ge yuè le.",j:"中国語を勉強して3か月になります。",e:"I've been learning Chinese for three months.",k:"중국어를 배운 지 3개월 됐습니다."}},
{w:"十",py:"shí",zy:"ㄕˊ",c:"數",m:{j:"十",e:"ten",k:"십, 열"},ex:{z:"這個十塊錢。",py:"Zhège shí kuài qián.",j:"これは10元です。",e:"This is ten dollars (NTD).",k:"이것은 10위안(NTD)입니다."}},
{w:"百",py:"bǎi",zy:"ㄅㄞˇ",c:"數",m:{j:"百",e:"hundred",k:"백"},ex:{z:"一共三百五十塊。",py:"Yígòng sānbǎi wǔshí kuài.",j:"全部で350元です。",e:"That's 350 dollars in total.",k:"전부 350위안입니다."}},
{w:"錢",py:"qián",zy:"ㄑㄧㄢˊ",c:"名",m:{j:"お金",e:"money",k:"돈"},ex:{z:"這個多少錢？",py:"Zhège duōshǎo qián?",j:"これはいくらですか。",e:"How much is this?",k:"이거 얼마예요?"}},
{w:"塊",py:"kuài",zy:"ㄎㄨㄞˋ",c:"量",m:{j:"元（お金の口語）",e:"dollar (colloquial)",k:"위안 (구어)"},ex:{z:"珍奶一杯五十塊。",py:"Zhēnnǎi yì bēi wǔshí kuài.",j:"タピオカミルクティーは一杯50元です。",e:"Bubble tea is fifty dollars a cup.",k:"버블티는 한 잔에 50위안입니다."}},
{w:"個",py:"ge",zy:"˙ㄍㄜ",c:"量",m:{j:"〜個（最も基本の量詞）",e:"(general measure word)",k:"~개 (기본 양사)"},ex:{z:"給我一個小籠包。",py:"Gěi wǒ yí ge xiǎolóngbāo.",j:"小籠包を一つください。",e:"Give me one soup dumpling.",k:"샤오룽바오 하나 주세요."}},
{w:"杯",py:"bēi",zy:"ㄅㄟ",c:"量",m:{j:"〜杯",e:"cup of; glass of",k:"~잔"},ex:{z:"兩杯冰奶茶，謝謝。",py:"Liǎng bēi bīng nǎichá, xièxie.",j:"アイスミルクティーを2杯、お願いします。",e:"Two iced milk teas, please.",k:"아이스 밀크티 두 잔 주세요."}},
// ── 動詞 ──
{w:"是",py:"shì",zy:"ㄕˋ",c:"動",m:{j:"〜です・〜である",e:"to be",k:"~이다"},ex:{z:"我是工程師。",py:"Wǒ shì gōngchéngshī.",j:"私はエンジニアです。",e:"I am an engineer.",k:"저는 엔지니어입니다."}},
{w:"有",py:"yǒu",zy:"ㄧㄡˇ",c:"動",m:{j:"ある・いる・持っている",e:"to have; there is",k:"있다"},ex:{z:"你有悠遊卡嗎？",py:"Nǐ yǒu Yōuyóukǎ ma?",j:"悠遊カード（EasyCard）を持っていますか。",e:"Do you have an EasyCard?",k:"이지카드 있어요?"}},
{w:"去",py:"qù",zy:"ㄑㄩˋ",c:"動",m:{j:"行く",e:"to go",k:"가다"},ex:{z:"我明天去台南。",py:"Wǒ míngtiān qù Táinán.",j:"明日、台南へ行きます。",e:"I'm going to Tainan tomorrow.",k:"저는 내일 타이난에 갑니다."}},
{w:"來",py:"lái",zy:"ㄌㄞˊ",c:"動",m:{j:"来る",e:"to come",k:"오다"},ex:{z:"歡迎來台灣！",py:"Huānyíng lái Táiwān!",j:"ようこそ台湾へ！",e:"Welcome to Taiwan!",k:"대만에 오신 것을 환영합니다!"}},
{w:"吃",py:"chī",zy:"ㄔ",c:"動",m:{j:"食べる",e:"to eat",k:"먹다"},ex:{z:"你想吃什麼？",py:"Nǐ xiǎng chī shénme?",j:"何が食べたいですか。",e:"What do you want to eat?",k:"뭐 먹고 싶어요?"}},
{w:"喝",py:"hē",zy:"ㄏㄜ",c:"動",m:{j:"飲む",e:"to drink",k:"마시다"},ex:{z:"我不喝咖啡，我喝茶。",py:"Wǒ bù hē kāfēi, wǒ hē chá.",j:"コーヒーは飲みません、お茶を飲みます。",e:"I don't drink coffee; I drink tea.",k:"저는 커피는 안 마시고 차를 마십니다."}},
{w:"買",py:"mǎi",zy:"ㄇㄞˇ",c:"動",m:{j:"買う",e:"to buy",k:"사다"},ex:{z:"我想買一張悠遊卡。",py:"Wǒ xiǎng mǎi yì zhāng Yōuyóukǎ.",j:"悠遊カードを1枚買いたいです。",e:"I want to buy an EasyCard.",k:"이지카드 한 장 사고 싶습니다."}},
{w:"看",py:"kàn",zy:"ㄎㄢˋ",c:"動",m:{j:"見る・読む",e:"to look; to read; to watch",k:"보다"},ex:{z:"我喜歡看電影。",py:"Wǒ xǐhuān kàn diànyǐng.",j:"映画を見るのが好きです。",e:"I like watching movies.",k:"저는 영화 보는 것을 좋아합니다."}},
{w:"聽",py:"tīng",zy:"ㄊㄧㄥ",c:"動",m:{j:"聞く",e:"to listen",k:"듣다"},ex:{z:"我每天聽中文播客。",py:"Wǒ měitiān tīng Zhōngwén bòkè.",j:"毎日中国語のポッドキャストを聞きます。",e:"I listen to Chinese podcasts every day.",k:"저는 매일 중국어 팟캐스트를 듣습니다."}},
{w:"說",py:"shuō",zy:"ㄕㄨㄛ",c:"動",m:{j:"話す・言う",e:"to speak; to say",k:"말하다"},ex:{z:"請說慢一點。",py:"Qǐng shuō màn yìdiǎn.",j:"もう少しゆっくり話してください。",e:"Please speak a little slower.",k:"조금 천천히 말해 주세요."}},
{w:"寫",py:"xiě",zy:"ㄒㄧㄝˇ",c:"動",m:{j:"書く",e:"to write",k:"쓰다"},ex:{z:"繁體字很難寫。",py:"Fántǐzì hěn nán xiě.",j:"繁体字は書くのが難しいです。",e:"Traditional characters are hard to write.",k:"번체자는 쓰기 어렵습니다."}},
{w:"學",py:"xué",zy:"ㄒㄩㄝˊ",c:"動",m:{j:"学ぶ・習う",e:"to learn; to study",k:"배우다"},ex:{z:"我在學台灣華語。",py:"Wǒ zài xué Táiwān Huáyǔ.",j:"台湾華語を勉強しています。",e:"I'm learning Taiwanese Mandarin.",k:"저는 대만 화어를 배우고 있습니다."}},
{w:"工作",py:"gōngzuò",zy:"ㄍㄨㄥ ㄗㄨㄛˋ",c:"動",m:{j:"働く／仕事",e:"to work; job",k:"일하다; 일"},ex:{z:"我在日本工作。",py:"Wǒ zài Rìběn gōngzuò.",j:"私は日本で働いています。",e:"I work in Japan.",k:"저는 일본에서 일합니다."}},
{w:"喜歡",py:"xǐhuān",zy:"ㄒㄧˇ ㄏㄨㄢ",c:"動",m:{j:"好き・好む",e:"to like",k:"좋아하다"},ex:{z:"我很喜歡台灣的夜市。",py:"Wǒ hěn xǐhuān Táiwān de yèshì.",j:"台湾の夜市が大好きです。",e:"I really like Taiwan's night markets.",k:"저는 대만 야시장을 아주 좋아합니다."}},
{w:"要",py:"yào",zy:"ㄧㄠˋ",c:"動",m:{j:"欲しい・〜するつもり",e:"to want; will",k:"원하다; ~할 것이다"},ex:{z:"我要這個。",py:"Wǒ yào zhège.",j:"これをください。",e:"I want this one.",k:"이걸로 주세요."}},
{w:"想",py:"xiǎng",zy:"ㄒㄧㄤˇ",c:"動",m:{j:"〜したい・思う",e:"to want to; to think",k:"~하고 싶다; 생각하다"},ex:{z:"我想去九份看看。",py:"Wǒ xiǎng qù Jiǔfèn kànkan.",j:"九份へ行ってみたいです。",e:"I want to visit Jiufen.",k:"지우펀에 가 보고 싶습니다."}},
{w:"會",py:"huì",zy:"ㄏㄨㄟˋ",c:"動",m:{j:"できる（習得）・〜だろう",e:"can; will",k:"~할 수 있다; ~할 것이다"},ex:{z:"我會說一點中文。",py:"Wǒ huì shuō yìdiǎn Zhōngwén.",j:"中国語が少し話せます。",e:"I can speak a little Chinese.",k:"중국어를 조금 할 수 있습니다."}},
{w:"可以",py:"kěyǐ",zy:"ㄎㄜˇ ㄧˇ",c:"動",m:{j:"〜してもいい・できる",e:"may; can",k:"~해도 된다"},ex:{z:"可以刷卡嗎？",py:"Kěyǐ shuākǎ ma?",j:"カードで払えますか。",e:"Can I pay by card?",k:"카드로 계산해도 돼요?"}},
{w:"知道",py:"zhīdào",zy:"ㄓ ㄉㄠˋ",c:"動",m:{j:"知っている・分かる",e:"to know",k:"알다"},ex:{z:"我不知道怎麼走。",py:"Wǒ bù zhīdào zěnme zǒu.",j:"どう行けばいいか分かりません。",e:"I don't know how to get there.",k:"어떻게 가는지 모르겠습니다."}},
{w:"住",py:"zhù",zy:"ㄓㄨˋ",c:"動",m:{j:"住む・泊まる",e:"to live; to stay",k:"살다; 묵다"},ex:{z:"你住在哪裡？",py:"Nǐ zhù zài nǎlǐ?",j:"どこに住んでいますか。",e:"Where do you live?",k:"어디에 살아요?"}},
// ── 形容詞 ──
{w:"好",py:"hǎo",zy:"ㄏㄠˇ",c:"形",m:{j:"良い",e:"good",k:"좋다"},ex:{z:"好，沒問題！",py:"Hǎo, méi wèntí!",j:"はい、問題ありません！",e:"OK, no problem!",k:"네, 문제없어요!"}},
{w:"大",py:"dà",zy:"ㄉㄚˋ",c:"形",m:{j:"大きい",e:"big",k:"크다"},ex:{z:"這碗麵好大！",py:"Zhè wǎn miàn hǎo dà!",j:"この麺、すごく大盛り！",e:"This bowl of noodles is huge!",k:"이 국수 정말 크네요!"}},
{w:"小",py:"xiǎo",zy:"ㄒㄧㄠˇ",c:"形",m:{j:"小さい",e:"small",k:"작다"},ex:{z:"我要小杯的。",py:"Wǒ yào xiǎo bēi de.",j:"小さいサイズをください。",e:"I'll take the small size.",k:"작은 사이즈로 주세요."}},
{w:"多",py:"duō",zy:"ㄉㄨㄛ",c:"形",m:{j:"多い",e:"many; much",k:"많다"},ex:{z:"台北的咖啡店很多。",py:"Táiběi de kāfēidiàn hěn duō.",j:"台北はカフェがとても多いです。",e:"Taipei has many cafes.",k:"타이베이에는 카페가 아주 많습니다."}},
{w:"貴",py:"guì",zy:"ㄍㄨㄟˋ",c:"形",m:{j:"（値段が）高い",e:"expensive",k:"비싸다"},ex:{z:"太貴了！可以便宜一點嗎？",py:"Tài guì le! Kěyǐ piányí yìdiǎn ma?",j:"高すぎます！少し安くなりませんか。",e:"Too expensive! Can you make it cheaper?",k:"너무 비싸요! 좀 싸게 해 주실 수 있어요?"}},
{w:"便宜",py:"piányí",zy:"ㄆㄧㄢˊ ㄧˊ",c:"形",m:{j:"安い",e:"cheap",k:"싸다"},ex:{z:"夜市的東西很便宜。",py:"Yèshì de dōngxi hěn piányí.",j:"夜市のものはとても安いです。",e:"Things at the night market are cheap.",k:"야시장 물건은 아주 쌉니다."}},
{w:"好吃",py:"hǎochī",zy:"ㄏㄠˇ ㄔ",c:"形",m:{j:"（食べ物が）おいしい",e:"delicious (food)",k:"맛있다 (음식)"},ex:{z:"這個超好吃！",py:"Zhège chāo hǎochī!",j:"これ、めちゃくちゃおいしい！",e:"This is super delicious!",k:"이거 진짜 맛있어요!"}},
{w:"好喝",py:"hǎohē",zy:"ㄏㄠˇ ㄏㄜ",c:"形",m:{j:"（飲み物が）おいしい",e:"delicious (drink)",k:"맛있다 (음료)"},ex:{z:"這家的奶茶很好喝。",py:"Zhè jiā de nǎichá hěn hǎohē.",j:"この店のミルクティーはおいしいです。",e:"This shop's milk tea is really good.",k:"이 가게 밀크티는 아주 맛있습니다."}},
{w:"漂亮",py:"piàoliàng",zy:"ㄆㄧㄠˋ ㄌㄧㄤˋ",c:"形",m:{j:"きれい・美しい",e:"pretty; beautiful",k:"예쁘다"},ex:{z:"日月潭的風景很漂亮。",py:"Rìyuètán de fēngjǐng hěn piàoliàng.",j:"日月潭の景色はとてもきれいです。",e:"The scenery at Sun Moon Lake is beautiful.",k:"르웨탄의 풍경은 아주 아름답습니다."}},
{w:"熱",py:"rè",zy:"ㄖㄜˋ",c:"形",m:{j:"暑い・熱い",e:"hot",k:"덥다, 뜨겁다"},ex:{z:"台灣的夏天很熱。",py:"Táiwān de xiàtiān hěn rè.",j:"台湾の夏はとても暑いです。",e:"Summer in Taiwan is very hot.",k:"대만의 여름은 아주 덥습니다."}},
{w:"冷",py:"lěng",zy:"ㄌㄥˇ",c:"形",m:{j:"寒い・冷たい",e:"cold",k:"춥다, 차갑다"},ex:{z:"今天有點冷。",py:"Jīntiān yǒudiǎn lěng.",j:"今日はちょっと寒いです。",e:"It's a bit cold today.",k:"오늘은 좀 춥습니다."}},
{w:"忙",py:"máng",zy:"ㄇㄤˊ",c:"形",m:{j:"忙しい",e:"busy",k:"바쁘다"},ex:{z:"我最近很忙。",py:"Wǒ zuìjìn hěn máng.",j:"最近とても忙しいです。",e:"I've been very busy lately.",k:"요즘 아주 바쁩니다."}},
{w:"累",py:"lèi",zy:"ㄌㄟˋ",c:"形",m:{j:"疲れた",e:"tired",k:"피곤하다"},ex:{z:"今天走了一天，好累。",py:"Jīntiān zǒu le yì tiān, hǎo lèi.",j:"今日は一日歩いて、すごく疲れました。",e:"I walked all day today; I'm so tired.",k:"오늘 하루 종일 걸어서 너무 피곤해요."}},
{w:"開心",py:"kāixīn",zy:"ㄎㄞ ㄒㄧㄣ",c:"形",m:{j:"うれしい・楽しい",e:"happy",k:"기쁘다, 즐겁다"},ex:{z:"認識你很開心。",py:"Rènshì nǐ hěn kāixīn.",j:"お会いできてうれしいです。",e:"I'm happy to meet you.",k:"만나서 반갑습니다."}},
{w:"近",py:"jìn",zy:"ㄐㄧㄣˋ",c:"形",m:{j:"近い",e:"near; close",k:"가깝다"},ex:{z:"捷運站離飯店很近。",py:"Jiéyùn zhàn lí fàndiàn hěn jìn.",j:"MRTの駅はホテルからとても近いです。",e:"The MRT station is very close to the hotel.",k:"지하철역은 호텔에서 아주 가깝습니다."}},
{w:"遠",py:"yuǎn",zy:"ㄩㄢˇ",c:"形",m:{j:"遠い",e:"far",k:"멀다"},ex:{z:"九份離台北遠不遠？",py:"Jiǔfèn lí Táiběi yuǎn bù yuǎn?",j:"九份は台北から遠いですか。",e:"Is Jiufen far from Taipei?",k:"지우펀은 타이베이에서 멀어요?"}},
// ── 疑問詞・指示詞 ──
{w:"什麼",py:"shénme",zy:"ㄕㄣˊ ˙ㄇㄜ",c:"疑",m:{j:"何",e:"what",k:"무엇"},ex:{z:"這是什麼？",py:"Zhè shì shénme?",j:"これは何ですか。",e:"What is this?",k:"이것은 무엇입니까?"}},
{w:"誰",py:"shéi",zy:"ㄕㄟˊ",c:"疑",m:{j:"誰",e:"who",k:"누구"},ex:{z:"那個人是誰？",py:"Nàge rén shì shéi?",j:"あの人は誰ですか。",e:"Who is that person?",k:"저 사람은 누구예요?"}},
{w:"哪裡",py:"nǎlǐ",zy:"ㄋㄚˇ ㄌㄧˇ",c:"疑",m:{j:"どこ",e:"where",k:"어디"},ex:{z:"你想去哪裡？",py:"Nǐ xiǎng qù nǎlǐ?",j:"どこへ行きたいですか。",e:"Where do you want to go?",k:"어디에 가고 싶어요?"}},
{w:"幾",py:"jǐ",zy:"ㄐㄧˇ",c:"疑",m:{j:"いくつ（10以下）",e:"how many (small numbers)",k:"몇"},ex:{z:"你們幾位？",py:"Nǐmen jǐ wèi?",j:"何名様ですか。",e:"How many people (in your party)?",k:"몇 분이세요?"}},
{w:"多少",py:"duōshǎo",zy:"ㄉㄨㄛ ㄕㄠˇ",c:"疑",m:{j:"いくら・どれくらい",e:"how much; how many",k:"얼마"},ex:{z:"一個月的房租多少錢？",py:"Yí ge yuè de fángzū duōshǎo qián?",j:"1か月の家賃はいくらですか。",e:"How much is the monthly rent?",k:"한 달 집세가 얼마예요?"}},
{w:"怎麼",py:"zěnme",zy:"ㄗㄣˇ ˙ㄇㄜ",c:"疑",m:{j:"どうやって・どうして",e:"how; why",k:"어떻게"},ex:{z:"這個字怎麼念？",py:"Zhège zì zěnme niàn?",j:"この字はどう読みますか。",e:"How do you read this character?",k:"이 글자는 어떻게 읽어요?"}},
{w:"這",py:"zhè",zy:"ㄓㄜˋ",c:"代",m:{j:"これ・この",e:"this",k:"이, 이것"},ex:{z:"這是我的悠遊卡。",py:"Zhè shì wǒ de Yōuyóukǎ.",j:"これは私の悠遊カードです。",e:"This is my EasyCard.",k:"이것은 제 이지카드입니다."}},
{w:"那",py:"nà",zy:"ㄋㄚˋ",c:"代",m:{j:"それ・あれ",e:"that",k:"그, 저"},ex:{z:"那是什麼小吃？",py:"Nà shì shénme xiǎochī?",j:"あれは何の屋台グルメですか。",e:"What snack is that?",k:"저것은 무슨 간식이에요?"}},
// ── あいさつ・決まり文句 ──
{w:"你好",py:"nǐ hǎo",zy:"ㄋㄧˇ ㄏㄠˇ",c:"寒暄",m:{j:"こんにちは",e:"hello",k:"안녕하세요"},ex:{z:"你好，我是山田。",py:"Nǐ hǎo, wǒ shì Shāntián.",j:"こんにちは、山田です。",e:"Hello, I'm Yamada.",k:"안녕하세요, 야마다입니다."}},
{w:"謝謝",py:"xièxie",zy:"ㄒㄧㄝˋ ˙ㄒㄧㄝ",c:"寒暄",m:{j:"ありがとう",e:"thank you",k:"감사합니다"},ex:{z:"謝謝你的幫忙！",py:"Xièxie nǐ de bāngmáng!",j:"手伝ってくれてありがとう！",e:"Thanks for your help!",k:"도와줘서 감사합니다!"}},
{w:"不客氣",py:"bú kèqì",zy:"ㄅㄨˊ ㄎㄜˋ ㄑㄧˋ",c:"寒暄",m:{j:"どういたしまして",e:"you're welcome",k:"천만에요"},ex:{z:"不客氣，小事而已。",py:"Bú kèqì, xiǎoshì éryǐ.",j:"どういたしまして、大したことないですよ。",e:"You're welcome, it was nothing.",k:"천만에요, 별거 아니에요."}},
{w:"對不起",py:"duìbùqǐ",zy:"ㄉㄨㄟˋ ㄅㄨˋ ㄑㄧˇ",c:"寒暄",m:{j:"ごめんなさい",e:"sorry",k:"미안합니다"},ex:{z:"對不起，我遲到了。",py:"Duìbùqǐ, wǒ chídào le.",j:"すみません、遅れました。",e:"Sorry, I'm late.",k:"미안합니다, 늦었습니다."}},
{w:"不好意思",py:"bù hǎoyìsi",zy:"ㄅㄨˋ ㄏㄠˇ ㄧˋ ˙ㄙ",c:"寒暄",m:{j:"すみません（台湾で最頻出）",e:"excuse me; sorry (very common in Taiwan)",k:"실례합니다, 미안해요"},ex:{z:"不好意思，借過一下。",py:"Bù hǎoyìsi, jièguò yíxià.",j:"すみません、ちょっと通してください。",e:"Excuse me, coming through.",k:"실례합니다, 좀 지나갈게요."}},
{w:"沒關係",py:"méi guānxi",zy:"ㄇㄟˊ ㄍㄨㄢ ˙ㄒㄧ",c:"寒暄",m:{j:"大丈夫・気にしないで",e:"it's OK; no problem",k:"괜찮아요"},ex:{z:"沒關係，慢慢來。",py:"Méi guānxi, mànmàn lái.",j:"大丈夫、ゆっくりでいいですよ。",e:"It's fine, take your time.",k:"괜찮아요, 천천히 하세요."}},
{w:"再見",py:"zàijiàn",zy:"ㄗㄞˋ ㄐㄧㄢˋ",c:"寒暄",m:{j:"さようなら",e:"goodbye",k:"안녕히 가세요"},ex:{z:"再見，下次見！",py:"Zàijiàn, xià cì jiàn!",j:"さようなら、また今度！",e:"Bye, see you next time!",k:"안녕히 가세요, 다음에 봐요!"}},
{w:"請問",py:"qǐngwèn",zy:"ㄑㄧㄥˇ ㄨㄣˋ",c:"寒暄",m:{j:"お尋ねしますが（すみません）",e:"excuse me, may I ask...",k:"말씀 좀 묻겠습니다"},ex:{z:"請問，這裡可以坐嗎？",py:"Qǐngwèn, zhèlǐ kěyǐ zuò ma?",j:"すみません、ここに座ってもいいですか。",e:"Excuse me, may I sit here?",k:"실례지만, 여기 앉아도 돼요?"}},
{w:"老闆",py:"lǎobǎn",zy:"ㄌㄠˇ ㄅㄢˇ",c:"名",m:{j:"店主・大将（店員への呼びかけ）",e:"boss; shopkeeper (used to address staff)",k:"사장님 (가게 주인을 부를 때)"},ex:{z:"老闆，這個怎麼賣？",py:"Lǎobǎn, zhège zěnme mài?",j:"すみません（大将）、これはいくらですか。",e:"Boss, how much is this?",k:"사장님, 이거 어떻게 팔아요?"}},
// ── 数字・量詞 ──
{w:"四",py:"sì",zy:"ㄙˋ",c:"數",m:{j:"四・4",e:"four",k:"넷, 4"},ex:{z:"我們家有四個人。",py:"Wǒmen jiā yǒu sì ge rén.",j:"うちは4人家族です。",e:"There are four people in our family.",k:"우리 집은 네 식구입니다."}},
{w:"五",py:"wǔ",zy:"ㄨˇ",c:"數",m:{j:"五・5",e:"five",k:"다섯, 5"},ex:{z:"我五點下班。",py:"Wǒ wǔ diǎn xiàbān.",j:"私は5時に退勤します。",e:"I get off work at five.",k:"저는 다섯 시에 퇴근합니다."}},
{w:"六",py:"liù",zy:"ㄌㄧㄡˋ",c:"數",m:{j:"六・6",e:"six",k:"여섯, 6"},ex:{z:"我早上六點起床。",py:"Wǒ zǎoshang liù diǎn qǐchuáng.",j:"私は朝6時に起きます。",e:"I get up at six in the morning.",k:"저는 아침 여섯 시에 일어납니다."}},
{w:"七",py:"qī",zy:"ㄑㄧ",c:"數",m:{j:"七・7",e:"seven",k:"일곱, 7"},ex:{z:"現在七點半。",py:"Xiànzài qī diǎn bàn.",j:"今は7時半です。",e:"It is seven thirty now.",k:"지금은 일곱 시 반입니다."}},
{w:"八",py:"bā",zy:"ㄅㄚ",c:"數",m:{j:"八・8",e:"eight",k:"여덟, 8"},ex:{z:"這杯咖啡八十塊。",py:"Zhè bēi kāfēi bāshí kuài.",j:"このコーヒーは80元です。",e:"This coffee is eighty NT dollars.",k:"이 커피는 80위안입니다."}},
{w:"九",py:"jiǔ",zy:"ㄐㄧㄡˇ",c:"數",m:{j:"九・9",e:"nine",k:"아홉, 9"},ex:{z:"我九點要開會。",py:"Wǒ jiǔ diǎn yào kāihuì.",j:"私は9時に会議があります。",e:"I have a meeting at nine.",k:"저는 아홉 시에 회의가 있습니다."}},
{w:"千",py:"qiān",zy:"ㄑㄧㄢ",c:"數",m:{j:"千",e:"thousand",k:"천"},ex:{z:"這件衣服一千塊。",py:"Zhè jiàn yīfú yìqiān kuài.",j:"この服は千元です。",e:"This piece of clothing is one thousand NT dollars.",k:"이 옷은 천 위안입니다."}},
{w:"萬",py:"wàn",zy:"ㄨㄢˋ",c:"數",m:{j:"万",e:"ten thousand",k:"만"},ex:{z:"這支手機兩萬塊。",py:"Zhè zhī shǒujī liǎng wàn kuài.",j:"この携帯は2万元です。",e:"This phone is twenty thousand NT dollars.",k:"이 휴대폰은 2만 위안입니다."}},
{w:"隻",py:"zhī",zy:"ㄓ",c:"量",m:{j:"〜匹・〜羽（動物の助数詞）",e:"measure word for animals",k:"마리 (동물 세는 단위)"},ex:{z:"我家有一隻貓。",py:"Wǒ jiā yǒu yì zhī māo.",j:"うちには猫が1匹います。",e:"I have a cat at home.",k:"우리 집에는 고양이 한 마리가 있습니다."}},
{w:"本",py:"běn",zy:"ㄅㄣˇ",c:"量",m:{j:"〜冊（本の助数詞）",e:"measure word for books",k:"권 (책 세는 단위)"},ex:{z:"我買了三本書。",py:"Wǒ mǎi le sān běn shū.",j:"私は本を3冊買いました。",e:"I bought three books.",k:"저는 책을 세 권 샀습니다."}},
// ── 曜日・日付 ──
{w:"星期一",py:"xīngqíyī",zy:"ㄒㄧㄥ ㄑㄧˊ ㄧ",c:"名",m:{j:"月曜日",e:"Monday",k:"월요일"},ex:{z:"我星期一要上班。",py:"Wǒ xīngqíyī yào shàngbān.",j:"私は月曜日に仕事があります。",e:"I have to work on Monday.",k:"저는 월요일에 출근해야 합니다."}},
{w:"星期日",py:"xīngqírì",zy:"ㄒㄧㄥ ㄑㄧˊ ㄖˋ",c:"名",m:{j:"日曜日",e:"Sunday",k:"일요일"},ex:{z:"星期日我在家休息。",py:"Xīngqírì wǒ zài jiā xiūxí.",j:"日曜日は家で休みます。",e:"I rest at home on Sunday.",k:"일요일에는 집에서 쉽니다."}},
{w:"月",py:"yuè",zy:"ㄩㄝˋ",c:"名",m:{j:"月（つき）",e:"month",k:"월, 달"},ex:{z:"一年有十二個月。",py:"Yì nián yǒu shí'èr ge yuè.",j:"1年は12か月あります。",e:"A year has twelve months.",k:"일 년은 열두 달입니다."}},
{w:"號",py:"hào",zy:"ㄏㄠˋ",c:"量",m:{j:"〜日（日付）・番号",e:"day of the month; number",k:"일 (날짜), 번호"},ex:{z:"今天是七月五號。",py:"Jīntiān shì qīyuè wǔ hào.",j:"今日は7月5日です。",e:"Today is July fifth.",k:"오늘은 7월 5일입니다."}},
{w:"生日",py:"shēngrì",zy:"ㄕㄥ ㄖˋ",c:"名",m:{j:"誕生日",e:"birthday",k:"생일"},ex:{z:"我的生日是三月十號。",py:"Wǒ de shēngrì shì sānyuè shí hào.",j:"私の誕生日は3月10日です。",e:"My birthday is March tenth.",k:"제 생일은 3월 10일입니다."}},
// ── 色 ──
{w:"紅色",py:"hóngsè",zy:"ㄏㄨㄥˊ ㄙㄜˋ",c:"名",m:{j:"赤・赤色",e:"red",k:"빨간색"},ex:{z:"我喜歡紅色的衣服。",py:"Wǒ xǐhuān hóngsè de yīfú.",j:"私は赤い服が好きです。",e:"I like red clothes.",k:"저는 빨간색 옷을 좋아합니다."}},
{w:"藍色",py:"lánsè",zy:"ㄌㄢˊ ㄙㄜˋ",c:"名",m:{j:"青・青色",e:"blue",k:"파란색"},ex:{z:"他的機車是藍色的。",py:"Tā de jīchē shì lánsè de.",j:"彼のバイクは青色です。",e:"His scooter is blue.",k:"그의 오토바이는 파란색입니다."}},
{w:"白色",py:"báisè",zy:"ㄅㄞˊ ㄙㄜˋ",c:"名",m:{j:"白・白色",e:"white",k:"흰색"},ex:{z:"我想買白色的鞋子。",py:"Wǒ xiǎng mǎi báisè de xiézi.",j:"私は白い靴を買いたいです。",e:"I want to buy white shoes.",k:"저는 흰색 신발을 사고 싶습니다."}},
{w:"黑色",py:"hēisè",zy:"ㄏㄟ ㄙㄜˋ",c:"名",m:{j:"黒・黒色",e:"black",k:"검은색"},ex:{z:"這隻貓是黑色的。",py:"Zhè zhī māo shì hēisè de.",j:"この猫は黒色です。",e:"This cat is black.",k:"이 고양이는 검은색입니다."}},
{w:"綠色",py:"lǜsè",zy:"ㄌㄩˋ ㄙㄜˋ",c:"名",m:{j:"緑・緑色",e:"green",k:"초록색"},ex:{z:"我最喜歡綠色。",py:"Wǒ zuì xǐhuān lǜsè.",j:"私は緑色がいちばん好きです。",e:"I like green the most.",k:"저는 초록색을 제일 좋아합니다."}},
{w:"黃色",py:"huángsè",zy:"ㄏㄨㄤˊ ㄙㄜˋ",c:"名",m:{j:"黄色",e:"yellow",k:"노란색"},ex:{z:"台灣的計程車是黃色的。",py:"Táiwān de jìchéngchē shì huángsè de.",j:"台湾のタクシーは黄色です。",e:"Taxis in Taiwan are yellow.",k:"대만의 택시는 노란색입니다."}},
// ── 体 ──
{w:"頭",py:"tóu",zy:"ㄊㄡˊ",c:"名",m:{j:"頭",e:"head",k:"머리"},ex:{z:"我今天頭有一點痛。",py:"Wǒ jīntiān tóu yǒu yìdiǎn tòng.",j:"今日は頭が少し痛いです。",e:"My head hurts a little today.",k:"오늘 머리가 조금 아픕니다."}},
{w:"手",py:"shǒu",zy:"ㄕㄡˇ",c:"名",m:{j:"手",e:"hand",k:"손"},ex:{z:"他的手很大。",py:"Tā de shǒu hěn dà.",j:"彼の手はとても大きいです。",e:"His hands are very big.",k:"그의 손은 아주 큽니다."}},
{w:"腳",py:"jiǎo",zy:"ㄐㄧㄠˇ",c:"名",m:{j:"足・脚",e:"foot; leg",k:"발, 다리"},ex:{z:"走了一天，我的腳很痛。",py:"Zǒu le yì tiān, wǒ de jiǎo hěn tòng.",j:"一日中歩いて、足がとても痛いです。",e:"After walking all day, my feet really hurt.",k:"하루 종일 걸어서 발이 많이 아픕니다."}},
{w:"眼睛",py:"yǎnjīng",zy:"ㄧㄢˇ ㄐㄧㄥ",c:"名",m:{j:"目",e:"eye",k:"눈"},ex:{z:"她的眼睛很漂亮。",py:"Tā de yǎnjīng hěn piàoliang.",j:"彼女の目はとてもきれいです。",e:"Her eyes are very pretty.",k:"그녀의 눈은 아주 예쁩니다."}},
{w:"耳朵",py:"ěrduo",zy:"ㄦˇ ˙ㄉㄨㄛ",c:"名",m:{j:"耳",e:"ear",k:"귀"},ex:{z:"我的耳朵不太舒服。",py:"Wǒ de ěrduo bú tài shūfú.",j:"耳の調子があまり良くありません。",e:"My ear does not feel very well.",k:"귀가 좀 불편합니다."}},
{w:"嘴巴",py:"zuǐbā",zy:"ㄗㄨㄟˇ ㄅㄚ",c:"名",m:{j:"口",e:"mouth",k:"입"},ex:{z:"醫生說：請打開嘴巴。",py:"Yīshēng shuō: qǐng dǎkāi zuǐbā.",j:"医者は「口を開けてください」と言いました。",e:"The doctor said: please open your mouth.",k:"의사가 말했습니다: 입을 벌려 주세요."}},
// ── 動物 ──
{w:"狗",py:"gǒu",zy:"ㄍㄡˇ",c:"名",m:{j:"犬",e:"dog",k:"개"},ex:{z:"我每天帶狗去公園。",py:"Wǒ měitiān dài gǒu qù gōngyuán.",j:"私は毎日犬を公園に連れて行きます。",e:"I take my dog to the park every day.",k:"저는 매일 개를 데리고 공원에 갑니다."}},
{w:"貓",py:"māo",zy:"ㄇㄠ",c:"名",m:{j:"猫",e:"cat",k:"고양이"},ex:{z:"我家的貓很喜歡睡覺。",py:"Wǒ jiā de māo hěn xǐhuān shuìjiào.",j:"うちの猫は寝るのが大好きです。",e:"My cat loves sleeping.",k:"우리 집 고양이는 자는 것을 아주 좋아합니다."}},
{w:"鳥",py:"niǎo",zy:"ㄋㄧㄠˇ",c:"名",m:{j:"鳥",e:"bird",k:"새"},ex:{z:"公園裡有很多鳥。",py:"Gōngyuán lǐ yǒu hěn duō niǎo.",j:"公園にはたくさんの鳥がいます。",e:"There are many birds in the park.",k:"공원에는 새가 많이 있습니다."}},
{w:"魚",py:"yú",zy:"ㄩˊ",c:"名",m:{j:"魚",e:"fish",k:"물고기, 생선"},ex:{z:"我晚餐想吃魚。",py:"Wǒ wǎncān xiǎng chī yú.",j:"晩ご飯に魚が食べたいです。",e:"I want to eat fish for dinner.",k:"저는 저녁으로 생선을 먹고 싶습니다."}},
// ── 食べ物 ──
{w:"雞肉",py:"jīròu",zy:"ㄐㄧ ㄖㄡˋ",c:"名",m:{j:"鶏肉",e:"chicken (meat)",k:"닭고기"},ex:{z:"我要一個雞肉便當。",py:"Wǒ yào yí ge jīròu biàndāng.",j:"鶏肉弁当を一つください。",e:"I would like a chicken bento.",k:"닭고기 도시락 하나 주세요."}},
{w:"豬肉",py:"zhūròu",zy:"ㄓㄨ ㄖㄡˋ",c:"名",m:{j:"豚肉",e:"pork",k:"돼지고기"},ex:{z:"這家店的豬肉很好吃。",py:"Zhè jiā diàn de zhūròu hěn hǎochī.",j:"この店の豚肉はとてもおいしいです。",e:"The pork at this shop is delicious.",k:"이 가게의 돼지고기는 아주 맛있습니다."}},
{w:"牛肉",py:"niúròu",zy:"ㄋㄧㄡˊ ㄖㄡˋ",c:"名",m:{j:"牛肉",e:"beef",k:"소고기"},ex:{z:"我不吃牛肉。",py:"Wǒ bù chī niúròu.",j:"私は牛肉を食べません。",e:"I do not eat beef.",k:"저는 소고기를 먹지 않습니다."}},
{w:"蛋",py:"dàn",zy:"ㄉㄢˋ",c:"名",m:{j:"卵",e:"egg",k:"달걀"},ex:{z:"早餐我吃了兩個蛋。",py:"Zǎocān wǒ chī le liǎng ge dàn.",j:"朝ご飯に卵を2つ食べました。",e:"I ate two eggs for breakfast.",k:"아침에 달걀을 두 개 먹었습니다."}},
{w:"麵包",py:"miànbāo",zy:"ㄇㄧㄢˋ ㄅㄠ",c:"名",m:{j:"パン",e:"bread",k:"빵"},ex:{z:"我早上買了麵包。",py:"Wǒ zǎoshang mǎi le miànbāo.",j:"朝、パンを買いました。",e:"I bought bread this morning.",k:"아침에 빵을 샀습니다."}},
{w:"湯",py:"tāng",zy:"ㄊㄤ",c:"名",m:{j:"スープ",e:"soup",k:"국, 수프"},ex:{z:"這碗湯很好喝。",py:"Zhè wǎn tāng hěn hǎohē.",j:"このスープはとてもおいしいです。",e:"This soup is very tasty.",k:"이 국은 아주 맛있습니다."}},
// ── 飲み物 ──
{w:"果汁",py:"guǒzhī",zy:"ㄍㄨㄛˇ ㄓ",c:"名",m:{j:"ジュース",e:"juice",k:"주스"},ex:{z:"老闆，我要一杯果汁。",py:"Lǎobǎn, wǒ yào yì bēi guǒzhī.",j:"すみません、ジュースを一杯ください。",e:"Boss, I would like a glass of juice.",k:"사장님, 주스 한 잔 주세요."}},
{w:"牛奶",py:"niúnǎi",zy:"ㄋㄧㄡˊ ㄋㄞˇ",c:"名",m:{j:"牛乳・ミルク",e:"milk",k:"우유"},ex:{z:"我每天早上喝牛奶。",py:"Wǒ měitiān zǎoshang hē niúnǎi.",j:"私は毎朝牛乳を飲みます。",e:"I drink milk every morning.",k:"저는 매일 아침 우유를 마십니다."}},
{w:"可樂",py:"kělè",zy:"ㄎㄜˇ ㄌㄜˋ",c:"名",m:{j:"コーラ",e:"cola",k:"콜라"},ex:{z:"他不喝咖啡，只喝可樂。",py:"Tā bù hē kāfēi, zhǐ hē kělè.",j:"彼はコーヒーを飲まず、コーラだけ飲みます。",e:"He does not drink coffee, only cola.",k:"그는 커피는 안 마시고 콜라만 마십니다."}},
{w:"冰塊",py:"bīngkuài",zy:"ㄅㄧㄥ ㄎㄨㄞˋ",c:"名",m:{j:"氷",e:"ice (cubes)",k:"얼음"},ex:{z:"請不要加冰塊，謝謝。",py:"Qǐng bú yào jiā bīngkuài, xièxie.",j:"氷は入れないでください。",e:"Please do not add ice, thank you.",k:"얼음은 넣지 말아 주세요, 감사합니다."}},
// ── 場所（追加）──
{w:"公園",py:"gōngyuán",zy:"ㄍㄨㄥ ㄩㄢˊ",c:"名",m:{j:"公園",e:"park",k:"공원"},ex:{z:"我早上去公園走走。",py:"Wǒ zǎoshang qù gōngyuán zǒuzou.",j:"朝、公園を散歩します。",e:"I take a walk in the park in the morning.",k:"아침에 공원에 산책하러 갑니다."}},
{w:"圖書館",py:"túshūguǎn",zy:"ㄊㄨˊ ㄕㄨ ㄍㄨㄢˇ",c:"名",m:{j:"図書館",e:"library",k:"도서관"},ex:{z:"我常常去圖書館看書。",py:"Wǒ chángcháng qù túshūguǎn kàn shū.",j:"私はよく図書館へ本を読みに行きます。",e:"I often go to the library to read.",k:"저는 자주 도서관에 책을 읽으러 갑니다."}},
{w:"郵局",py:"yóujú",zy:"ㄧㄡˊ ㄐㄩˊ",c:"名",m:{j:"郵便局",e:"post office",k:"우체국"},ex:{z:"我要去郵局寄東西。",py:"Wǒ yào qù yóujú jì dōngxi.",j:"郵便局へ荷物を送りに行きます。",e:"I am going to the post office to mail something.",k:"우체국에 물건을 부치러 갑니다."}},
{w:"超市",py:"chāoshì",zy:"ㄔㄠ ㄕˋ",c:"名",m:{j:"スーパー",e:"supermarket",k:"슈퍼마켓"},ex:{z:"媽媽在超市買水果。",py:"Māma zài chāoshì mǎi shuǐguǒ.",j:"母はスーパーで果物を買います。",e:"Mom buys fruit at the supermarket.",k:"엄마는 슈퍼에서 과일을 삽니다."}},
{w:"飯店",py:"fàndiàn",zy:"ㄈㄢˋ ㄉㄧㄢˋ",c:"名",m:{j:"ホテル",e:"hotel",k:"호텔"},ex:{z:"我們住台北的飯店。",py:"Wǒmen zhù Táiběi de fàndiàn.",j:"私たちは台北のホテルに泊まります。",e:"We are staying at a hotel in Taipei.",k:"우리는 타이베이의 호텔에 묵습니다."}},
{w:"教室",py:"jiàoshì",zy:"ㄐㄧㄠˋ ㄕˋ",c:"名",m:{j:"教室",e:"classroom",k:"교실"},ex:{z:"學生都在教室裡。",py:"Xuéshēng dōu zài jiàoshì lǐ.",j:"学生はみんな教室にいます。",e:"The students are all in the classroom.",k:"학생들은 모두 교실에 있습니다."}},
{w:"大學",py:"dàxué",zy:"ㄉㄚˋ ㄒㄩㄝˊ",c:"名",m:{j:"大学",e:"university",k:"대학교"},ex:{z:"他在大學學中文。",py:"Tā zài dàxué xué Zhōngwén.",j:"彼は大学で中国語を勉強しています。",e:"He studies Chinese at university.",k:"그는 대학에서 중국어를 공부합니다."}},
// ── 日常の物 ──
{w:"桌子",py:"zhuōzi",zy:"ㄓㄨㄛ ˙ㄗ",c:"名",m:{j:"机・テーブル",e:"table; desk",k:"책상, 테이블"},ex:{z:"桌子上有一杯茶。",py:"Zhuōzi shàng yǒu yì bēi chá.",j:"テーブルの上にお茶が一杯あります。",e:"There is a cup of tea on the table.",k:"테이블 위에 차가 한 잔 있습니다."}},
{w:"椅子",py:"yǐzi",zy:"ㄧˇ ˙ㄗ",c:"名",m:{j:"椅子",e:"chair",k:"의자"},ex:{z:"這張椅子很舒服。",py:"Zhè zhāng yǐzi hěn shūfú.",j:"この椅子はとても座り心地がいいです。",e:"This chair is very comfortable.",k:"이 의자는 아주 편합니다."}},
{w:"床",py:"chuáng",zy:"ㄔㄨㄤˊ",c:"名",m:{j:"ベッド",e:"bed",k:"침대"},ex:{z:"我的房間有一張床。",py:"Wǒ de fángjiān yǒu yì zhāng chuáng.",j:"私の部屋にはベッドが一つあります。",e:"There is a bed in my room.",k:"제 방에는 침대가 하나 있습니다."}},
{w:"門",py:"mén",zy:"ㄇㄣˊ",c:"名",m:{j:"ドア・門",e:"door; gate",k:"문"},ex:{z:"請關門，謝謝。",py:"Qǐng guān mén, xièxie.",j:"ドアを閉めてください。",e:"Please close the door, thank you.",k:"문을 닫아 주세요, 감사합니다."}},
{w:"窗戶",py:"chuānghù",zy:"ㄔㄨㄤ ㄏㄨˋ",c:"名",m:{j:"窓",e:"window",k:"창문"},ex:{z:"房間的窗戶很大。",py:"Fángjiān de chuānghù hěn dà.",j:"部屋の窓はとても大きいです。",e:"The window in the room is very big.",k:"방의 창문이 아주 큽니다."}},
{w:"書",py:"shū",zy:"ㄕㄨ",c:"名",m:{j:"本",e:"book",k:"책"},ex:{z:"我在看一本日文書。",py:"Wǒ zài kàn yì běn Rìwén shū.",j:"私は日本語の本を読んでいます。",e:"I am reading a Japanese book.",k:"저는 일본어 책을 읽고 있습니다."}},
{w:"筆",py:"bǐ",zy:"ㄅㄧˇ",c:"名",m:{j:"ペン・筆記具",e:"pen",k:"펜"},ex:{z:"可以借我一支筆嗎？",py:"Kěyǐ jiè wǒ yì zhī bǐ ma?",j:"ペンを1本貸してもらえますか。",e:"Could you lend me a pen?",k:"펜 하나 빌려줄 수 있어요?"}},
{w:"傘",py:"sǎn",zy:"ㄙㄢˇ",c:"名",m:{j:"傘",e:"umbrella",k:"우산"},ex:{z:"外面下雨，你要帶傘。",py:"Wàimiàn xiàyǔ, nǐ yào dài sǎn.",j:"外は雨だから、傘を持って行ってね。",e:"It is raining outside; you should take an umbrella.",k:"밖에 비가 오니까 우산을 가져가야 해요."}},
{w:"眼鏡",py:"yǎnjìng",zy:"ㄧㄢˇ ㄐㄧㄥˋ",c:"名",m:{j:"眼鏡",e:"glasses",k:"안경"},ex:{z:"我的眼鏡不見了！",py:"Wǒ de yǎnjìng bújiàn le!",j:"眼鏡がなくなりました！",e:"My glasses are gone!",k:"제 안경이 없어졌어요!"}},
// ── 家族（追加）──
{w:"爺爺",py:"yéye",zy:"ㄧㄝˊ ˙ㄧㄝ",c:"名",m:{j:"おじいさん（父方）",e:"grandfather (paternal)",k:"할아버지 (친가)"},ex:{z:"爺爺今年八十歲。",py:"Yéye jīnnián bāshí suì.",j:"祖父は今年80歳です。",e:"Grandpa is eighty years old this year.",k:"할아버지는 올해 여든 살입니다."}},
{w:"奶奶",py:"nǎinai",zy:"ㄋㄞˇ ˙ㄋㄞ",c:"名",m:{j:"おばあさん（父方）",e:"grandmother (paternal)",k:"할머니 (친가)"},ex:{z:"奶奶每天早上去公園。",py:"Nǎinai měitiān zǎoshang qù gōngyuán.",j:"祖母は毎朝公園に行きます。",e:"Grandma goes to the park every morning.",k:"할머니는 매일 아침 공원에 갑니다."}},
{w:"兒子",py:"érzi",zy:"ㄦˊ ˙ㄗ",c:"名",m:{j:"息子",e:"son",k:"아들"},ex:{z:"他的兒子今年五歲。",py:"Tā de érzi jīnnián wǔ suì.",j:"彼の息子は今年5歳です。",e:"His son is five years old this year.",k:"그의 아들은 올해 다섯 살입니다."}},
{w:"女兒",py:"nǚ'ér",zy:"ㄋㄩˇ ㄦˊ",c:"名",m:{j:"娘",e:"daughter",k:"딸"},ex:{z:"她的女兒是大學生。",py:"Tā de nǚ'ér shì dàxuéshēng.",j:"彼女の娘は大学生です。",e:"Her daughter is a university student.",k:"그녀의 딸은 대학생입니다."}},
// ── 基本動詞（追加）──
{w:"開",py:"kāi",zy:"ㄎㄞ",c:"動",m:{j:"開ける・（電源を）つける",e:"to open; to turn on",k:"열다, 켜다"},ex:{z:"天氣好熱，我開冷氣了。",py:"Tiānqì hǎo rè, wǒ kāi lěngqì le.",j:"すごく暑いので、エアコンをつけました。",e:"It is so hot; I turned on the air conditioner.",k:"날씨가 너무 더워서 에어컨을 켰어요."}},
{w:"關",py:"guān",zy:"ㄍㄨㄢ",c:"動",m:{j:"閉める・（電源を）消す",e:"to close; to turn off",k:"닫다, 끄다"},ex:{z:"出門前要關冷氣。",py:"Chūmén qián yào guān lěngqì.",j:"出かける前にエアコンを消してください。",e:"Turn off the air conditioner before going out.",k:"나가기 전에 에어컨을 꺼야 해요."}},
{w:"坐",py:"zuò",zy:"ㄗㄨㄛˋ",c:"動",m:{j:"座る・（乗り物に）乗る",e:"to sit; to take (transport)",k:"앉다, 타다"},ex:{z:"請坐，喝杯茶。",py:"Qǐng zuò, hē bēi chá.",j:"どうぞ座って、お茶を飲んでください。",e:"Please sit down and have some tea.",k:"앉으세요, 차 한잔 드세요."}},
{w:"走",py:"zǒu",zy:"ㄗㄡˇ",c:"動",m:{j:"歩く・行く",e:"to walk; to go",k:"걷다, 가다"},ex:{z:"車站很近，我們走過去吧。",py:"Chēzhàn hěn jìn, wǒmen zǒu guòqù ba.",j:"駅は近いから、歩いて行きましょう。",e:"The station is close; let's walk there.",k:"역이 가까우니까 걸어서 가요."}},
{w:"拿",py:"ná",zy:"ㄋㄚˊ",c:"動",m:{j:"持つ・取る",e:"to take; to hold",k:"들다, 가지다"},ex:{z:"這個很重，我幫你拿。",py:"Zhège hěn zhòng, wǒ bāng nǐ ná.",j:"これは重いから、私が持ちますよ。",e:"This is heavy; let me carry it for you.",k:"이거 무거우니까 제가 들어 드릴게요."}},
{w:"用",py:"yòng",zy:"ㄩㄥˋ",c:"動",m:{j:"使う",e:"to use",k:"쓰다, 사용하다"},ex:{z:"可以用一下你的筆嗎？",py:"Kěyǐ yòng yíxià nǐ de bǐ ma?",j:"ちょっとペンを使ってもいいですか。",e:"May I use your pen for a moment?",k:"펜 좀 써도 될까요?"}},
{w:"做",py:"zuò",zy:"ㄗㄨㄛˋ",c:"動",m:{j:"する・作る",e:"to do; to make",k:"하다, 만들다"},ex:{z:"這是我媽媽做的菜。",py:"Zhè shì wǒ māma zuò de cài.",j:"これは母が作った料理です。",e:"This is a dish my mom made.",k:"이건 엄마가 만든 요리예요."}},
{w:"玩",py:"wán",zy:"ㄨㄢˊ",c:"動",m:{j:"遊ぶ",e:"to play; to have fun",k:"놀다"},ex:{z:"我們週末去台南玩吧！",py:"Wǒmen zhōumò qù Táinán wán ba!",j:"週末に台南へ遊びに行きましょう！",e:"Let's go have fun in Tainan this weekend!",k:"주말에 타이난에 놀러 가요!"}},
{w:"問",py:"wèn",zy:"ㄨㄣˋ",c:"動",m:{j:"聞く・尋ねる",e:"to ask",k:"묻다"},ex:{z:"不知道的話，可以問老師。",py:"Bù zhīdào dehuà, kěyǐ wèn lǎoshī.",j:"分からなければ、先生に聞いてもいいですよ。",e:"If you don't know, you can ask the teacher.",k:"모르면 선생님께 물어봐도 돼요."}},
{w:"洗",py:"xǐ",zy:"ㄒㄧˇ",c:"動",m:{j:"洗う",e:"to wash",k:"씻다"},ex:{z:"吃飯前要洗手。",py:"Chīfàn qián yào xǐ shǒu.",j:"ご飯の前に手を洗いましょう。",e:"Wash your hands before eating.",k:"밥 먹기 전에 손을 씻어야 해요."}},
{w:"找",py:"zhǎo",zy:"ㄓㄠˇ",c:"動",m:{j:"探す",e:"to look for",k:"찾다"},ex:{z:"我在找我的手機。",py:"Wǒ zài zhǎo wǒ de shǒujī.",j:"携帯を探しています。",e:"I am looking for my phone.",k:"제 휴대폰을 찾고 있어요."}},
{w:"教",py:"jiāo",zy:"ㄐㄧㄠ",c:"動",m:{j:"教える",e:"to teach",k:"가르치다"},ex:{z:"你可以教我做這個菜嗎？",py:"Nǐ kěyǐ jiāo wǒ zuò zhège cài ma?",j:"この料理の作り方を教えてくれますか。",e:"Can you teach me how to make this dish?",k:"이 요리 만드는 법을 가르쳐 줄 수 있어요?"}},
{w:"認識",py:"rènshì",zy:"ㄖㄣˋ ㄕˋ",c:"動",m:{j:"知り合う・見知っている",e:"to know (a person); to meet",k:"알다, 알게 되다"},ex:{z:"很高興認識你！",py:"Hěn gāoxìng rènshì nǐ!",j:"お会いできてうれしいです！",e:"Nice to meet you!",k:"만나서 반갑습니다!"}},
// ── 基本形容詞（追加）──
{w:"高",py:"gāo",zy:"ㄍㄠ",c:"形",m:{j:"高い（高さ・背）",e:"tall; high",k:"높다, (키가) 크다"},ex:{z:"台北一〇一很高。",py:"Táiběi yīlíngyī hěn gāo.",j:"台北101はとても高いです。",e:"Taipei 101 is very tall.",k:"타이베이 101은 아주 높습니다."}},
{w:"長",py:"cháng",zy:"ㄔㄤˊ",c:"形",m:{j:"長い",e:"long",k:"길다"},ex:{z:"她的頭髮很長。",py:"Tā de tóufǎ hěn cháng.",j:"彼女の髪はとても長いです。",e:"Her hair is very long.",k:"그녀의 머리카락은 아주 깁니다."}},
{w:"短",py:"duǎn",zy:"ㄉㄨㄢˇ",c:"形",m:{j:"短い",e:"short (length)",k:"짧다"},ex:{z:"這件褲子太短了。",py:"Zhè jiàn kùzi tài duǎn le.",j:"このズボンは短すぎます。",e:"These pants are too short.",k:"이 바지는 너무 짧아요."}},
{w:"快",py:"kuài",zy:"ㄎㄨㄞˋ",c:"形",m:{j:"速い",e:"fast",k:"빠르다"},ex:{z:"高鐵很快，一個半小時就到了。",py:"Gāotiě hěn kuài, yí ge bàn xiǎoshí jiù dào le.",j:"高鉄は速くて、1時間半で着きます。",e:"The high-speed rail is fast; it arrives in an hour and a half.",k:"고속철도는 빨라서 한 시간 반이면 도착해요."}},
{w:"慢",py:"màn",zy:"ㄇㄢˋ",c:"形",m:{j:"遅い・ゆっくり",e:"slow",k:"느리다"},ex:{z:"不好意思，請說慢一點。",py:"Bùhǎoyìsi, qǐng shuō màn yìdiǎn.",j:"すみません、もう少しゆっくり話してください。",e:"Sorry, please speak a little more slowly.",k:"죄송하지만 조금 천천히 말해 주세요."}},
{w:"新",py:"xīn",zy:"ㄒㄧㄣ",c:"形",m:{j:"新しい",e:"new",k:"새롭다"},ex:{z:"我買了新手機。",py:"Wǒ mǎi le xīn shǒujī.",j:"新しい携帯を買いました。",e:"I bought a new phone.",k:"새 휴대폰을 샀어요."}},
{w:"早",py:"zǎo",zy:"ㄗㄠˇ",c:"形",m:{j:"早い（時間）",e:"early",k:"이르다"},ex:{z:"我明天要早一點起床。",py:"Wǒ míngtiān yào zǎo yìdiǎn qǐchuáng.",j:"明日は少し早めに起きないといけません。",e:"I need to get up a bit earlier tomorrow.",k:"내일은 좀 일찍 일어나야 해요."}},
{w:"晚",py:"wǎn",zy:"ㄨㄢˇ",c:"形",m:{j:"遅い（時刻）",e:"late",k:"늦다"},ex:{z:"現在很晚了，我要睡覺了。",py:"Xiànzài hěn wǎn le, wǒ yào shuìjiào le.",j:"もう遅いので、寝ます。",e:"It is very late now; I am going to sleep.",k:"이제 많이 늦어서 자야겠어요."}},
// ── 時間（追加）──
{w:"上午",py:"shàngwǔ",zy:"ㄕㄤˋ ㄨˇ",c:"名",m:{j:"午前",e:"morning; a.m.",k:"오전"},ex:{z:"我上午有中文課。",py:"Wǒ shàngwǔ yǒu Zhōngwén kè.",j:"午前中に中国語の授業があります。",e:"I have Chinese class in the morning.",k:"저는 오전에 중국어 수업이 있습니다."}},
{w:"下午",py:"xiàwǔ",zy:"ㄒㄧㄚˋ ㄨˇ",c:"名",m:{j:"午後",e:"afternoon; p.m.",k:"오후"},ex:{z:"下午我們去逛街吧。",py:"Xiàwǔ wǒmen qù guàngjiē ba.",j:"午後、買い物に行きましょう。",e:"Let's go shopping this afternoon.",k:"오후에 쇼핑하러 가요."}},
{w:"週末",py:"zhōumò",zy:"ㄓㄡ ㄇㄛˋ",c:"名",m:{j:"週末",e:"weekend",k:"주말"},ex:{z:"這個週末我想去爬山。",py:"Zhège zhōumò wǒ xiǎng qù páshān.",j:"今週末は山登りに行きたいです。",e:"I want to go hiking this weekend.",k:"이번 주말에 등산하러 가고 싶어요."}},
{w:"每天",py:"měitiān",zy:"ㄇㄟˇ ㄊㄧㄢ",c:"副",m:{j:"毎日",e:"every day",k:"매일"},ex:{z:"我每天喝一杯咖啡。",py:"Wǒ měitiān hē yì bēi kāfēi.",j:"私は毎日コーヒーを1杯飲みます。",e:"I drink a cup of coffee every day.",k:"저는 매일 커피를 한 잔 마십니다."}},
{w:"年",py:"nián",zy:"ㄋㄧㄢˊ",c:"名",m:{j:"年（とし）",e:"year",k:"년, 해"},ex:{z:"我來台灣一年了。",py:"Wǒ lái Táiwān yì nián le.",j:"台湾に来て1年になります。",e:"I have been in Taiwan for a year.",k:"대만에 온 지 1년이 되었습니다."}},
// ── その他 ──
{w:"自己",py:"zìjǐ",zy:"ㄗˋ ㄐㄧˇ",c:"代",m:{j:"自分",e:"oneself",k:"자기, 스스로"},ex:{z:"我自己一個人住。",py:"Wǒ zìjǐ yí ge rén zhù.",j:"私は一人暮らしです。",e:"I live by myself.",k:"저는 혼자 삽니다."}},
{w:"一起",py:"yìqǐ",zy:"ㄧˋ ㄑㄧˇ",c:"副",m:{j:"一緒に",e:"together",k:"같이, 함께"},ex:{z:"我們一起去吃飯吧！",py:"Wǒmen yìqǐ qù chīfàn ba!",j:"一緒にご飯を食べに行きましょう！",e:"Let's go eat together!",k:"우리 같이 밥 먹으러 가요!"}},
{w:"東西",py:"dōngxi",zy:"ㄉㄨㄥ ˙ㄒㄧ",c:"名",m:{j:"物・品物",e:"thing; stuff",k:"물건"},ex:{z:"我要去超市買東西。",py:"Wǒ yào qù chāoshì mǎi dōngxi.",j:"スーパーへ買い物に行きます。",e:"I am going to the supermarket to buy some things.",k:"슈퍼에 물건을 사러 갑니다."}},
// ── 量詞（第二輪追加） ──
{w:"條",py:"tiáo",zy:"ㄊㄧㄠˊ",c:"量",m:{j:"〜本・〜匹（細長いもの）",e:"measure word for long thin things",k:"~마리, ~개 (가늘고 긴 것)"},ex:{z:"我買了一條魚。",py:"Wǒ mǎi le yì tiáo yú.",j:"魚を一匹買いました。",e:"I bought a fish.",k:"생선 한 마리를 샀습니다."}},
{w:"位",py:"wèi",zy:"ㄨㄟˋ",c:"量",m:{j:"〜名様（人の敬称の量詞）",e:"measure word for people (polite)",k:"~분 (높임)"},ex:{z:"請問幾位？",py:"Qǐngwèn jǐ wèi?",j:"何名様ですか。",e:"How many people, please?",k:"몇 분이세요?"}},
{w:"台",py:"tái",zy:"ㄊㄞˊ",c:"量",m:{j:"〜台（機械）",e:"measure word for machines",k:"~대 (기계)"},ex:{z:"我家有兩台電腦。",py:"Wǒ jiā yǒu liǎng tái diànnǎo.",j:"うちにはパソコンが2台あります。",e:"There are two computers in my home.",k:"우리 집에는 컴퓨터가 두 대 있습니다."}},
{w:"次",py:"cì",zy:"ㄘˋ",c:"量",m:{j:"〜回・〜度",e:"time (occurrence)",k:"~번, ~회"},ex:{z:"我去過一次台南。",py:"Wǒ qùguò yí cì Táinán.",j:"台南に一度行ったことがあります。",e:"I have been to Tainan once.",k:"타이난에 한 번 가 본 적이 있습니다."}},
{w:"歲",py:"suì",zy:"ㄙㄨㄟˋ",c:"量",m:{j:"〜歳",e:"years old",k:"~살, ~세"},ex:{z:"我今年二十五歲。",py:"Wǒ jīnnián èrshíwǔ suì.",j:"私は今年25歳です。",e:"I am twenty-five this year.",k:"저는 올해 스물다섯 살입니다."}},
{w:"些",py:"xiē",zy:"ㄒㄧㄝ",c:"量",m:{j:"いくつか・少し",e:"some; a few",k:"몇몇, 약간"},ex:{z:"我買了一些水果。",py:"Wǒ mǎi le yìxiē shuǐguǒ.",j:"果物をいくつか買いました。",e:"I bought some fruit.",k:"과일을 조금 샀습니다."}},
// ── 食べ物・調味料（第二輪追加） ──
{w:"糖",py:"táng",zy:"ㄊㄤˊ",c:"名",m:{j:"砂糖",e:"sugar",k:"설탕"},ex:{z:"咖啡要加糖嗎？",py:"Kāfēi yào jiā táng ma?",j:"コーヒーに砂糖を入れますか。",e:"Do you want sugar in your coffee?",k:"커피에 설탕을 넣을까요?"}},
{w:"鹽",py:"yán",zy:"ㄧㄢˊ",c:"名",m:{j:"塩",e:"salt",k:"소금"},ex:{z:"請給我一點鹽。",py:"Qǐng gěi wǒ yìdiǎn yán.",j:"塩を少しください。",e:"Please give me a little salt.",k:"소금을 조금 주세요."}},
{w:"油",py:"yóu",zy:"ㄧㄡˊ",c:"名",m:{j:"油",e:"oil",k:"기름"},ex:{z:"媽媽做菜用很多油。",py:"Māma zuò cài yòng hěn duō yóu.",j:"母は料理に油をたくさん使います。",e:"My mom uses a lot of oil when cooking.",k:"엄마는 요리할 때 기름을 많이 씁니다."}},
{w:"醬油",py:"jiàngyóu",zy:"ㄐㄧㄤˋ ㄧㄡˊ",c:"名",m:{j:"醤油",e:"soy sauce",k:"간장"},ex:{z:"請給我醬油。",py:"Qǐng gěi wǒ jiàngyóu.",j:"醤油をください。",e:"Please give me some soy sauce.",k:"간장을 주세요."}},
{w:"水餃",py:"shuǐjiǎo",zy:"ㄕㄨㄟˇ ㄐㄧㄠˇ",c:"名",m:{j:"水餃子",e:"boiled dumpling",k:"물만두"},ex:{z:"這家店的水餃很好吃。",py:"Zhè jiā diàn de shuǐjiǎo hěn hǎochī.",j:"この店の水餃子はとてもおいしいです。",e:"The dumplings at this shop are delicious.",k:"이 가게의 물만두는 아주 맛있습니다."}},
{w:"包子",py:"bāozi",zy:"ㄅㄠ ˙ㄗ",c:"名",m:{j:"中華まん・肉まん",e:"steamed bun",k:"찐빵, 만두"},ex:{z:"我早餐吃了兩個包子。",py:"Wǒ zǎocān chī le liǎng ge bāozi.",j:"朝ごはんに肉まんを2つ食べました。",e:"I ate two steamed buns for breakfast.",k:"아침으로 찐빵 두 개를 먹었습니다."}},
{w:"豆腐",py:"dòufu",zy:"ㄉㄡˋ ˙ㄈㄨ",c:"名",m:{j:"豆腐",e:"tofu",k:"두부"},ex:{z:"這個湯裡有豆腐。",py:"Zhège tāng lǐ yǒu dòufu.",j:"このスープには豆腐が入っています。",e:"There is tofu in this soup.",k:"이 국에는 두부가 들어 있습니다."}},
{w:"青菜",py:"qīngcài",zy:"ㄑㄧㄥ ㄘㄞˋ",c:"名",m:{j:"青菜・野菜",e:"green vegetables",k:"푸성귀, 채소"},ex:{z:"老闆，我要一盤青菜。",py:"Lǎobǎn, wǒ yào yì pán qīngcài.",j:"すみません、青菜を一皿ください。",e:"Boss, I would like a plate of greens.",k:"사장님, 채소 한 접시 주세요."}},
{w:"蘋果",py:"píngguǒ",zy:"ㄆㄧㄥˊ ㄍㄨㄛˇ",c:"名",m:{j:"りんご",e:"apple",k:"사과"},ex:{z:"我每天吃一個蘋果。",py:"Wǒ měitiān chī yí ge píngguǒ.",j:"私は毎日りんごを1つ食べます。",e:"I eat an apple every day.",k:"저는 매일 사과를 한 개 먹습니다."}},
{w:"香蕉",py:"xiāngjiāo",zy:"ㄒㄧㄤ ㄐㄧㄠ",c:"名",m:{j:"バナナ",e:"banana",k:"바나나"},ex:{z:"台灣的香蕉很便宜。",py:"Táiwān de xiāngjiāo hěn piányí.",j:"台湾のバナナはとても安いです。",e:"Bananas in Taiwan are very cheap.",k:"대만의 바나나는 아주 쌉니다."}},
{w:"西瓜",py:"xīguā",zy:"ㄒㄧ ㄍㄨㄚ",c:"名",m:{j:"スイカ",e:"watermelon",k:"수박"},ex:{z:"這個西瓜很甜。",py:"Zhège xīguā hěn tián.",j:"このスイカはとても甘いです。",e:"This watermelon is very sweet.",k:"이 수박은 아주 답니다."}},
// ── 食器（第二輪追加） ──
{w:"叉子",py:"chāzi",zy:"ㄔㄚ ˙ㄗ",c:"名",m:{j:"フォーク",e:"fork",k:"포크"},ex:{z:"我要叉子，不要筷子。",py:"Wǒ yào chāzi, bú yào kuàizi.",j:"箸ではなくフォークをください。",e:"I want a fork, not chopsticks.",k:"젓가락 말고 포크를 주세요."}},
// ── 日用品（第二輪追加） ──
{w:"行李",py:"xínglǐ",zy:"ㄒㄧㄥˊ ㄌㄧˇ",c:"名",m:{j:"荷物",e:"luggage",k:"짐, 수하물"},ex:{z:"我的行李很重。",py:"Wǒ de xínglǐ hěn zhòng.",j:"私の荷物はとても重いです。",e:"My luggage is very heavy.",k:"제 짐은 아주 무겁습니다."}},
{w:"電話",py:"diànhuà",zy:"ㄉㄧㄢˋ ㄏㄨㄚˋ",c:"名",m:{j:"電話",e:"telephone",k:"전화"},ex:{z:"你的電話是幾號？",py:"Nǐ de diànhuà shì jǐ hào?",j:"あなたの電話番号は何番ですか。",e:"What is your phone number?",k:"전화번호가 몇 번이에요?"}},
{w:"照片",py:"zhàopiàn",zy:"ㄓㄠˋ ㄆㄧㄢˋ",c:"名",m:{j:"写真",e:"photo",k:"사진"},ex:{z:"這張照片很漂亮。",py:"Zhè zhāng zhàopiàn hěn piàoliàng.",j:"この写真はとてもきれいです。",e:"This photo is very beautiful.",k:"이 사진은 아주 예쁩니다."}},
{w:"報紙",py:"bàozhǐ",zy:"ㄅㄠˋ ㄓˇ",c:"名",m:{j:"新聞（紙）",e:"newspaper",k:"신문"},ex:{z:"爺爺每天早上看報紙。",py:"Yéye měitiān zǎoshang kàn bàozhǐ.",j:"おじいちゃんは毎朝新聞を読みます。",e:"Grandpa reads the newspaper every morning.",k:"할아버지는 매일 아침 신문을 봅니다."}},
{w:"雜誌",py:"zázhì",zy:"ㄗㄚˊ ㄓˋ",c:"名",m:{j:"雑誌",e:"magazine",k:"잡지"},ex:{z:"我在便利商店買了一本雜誌。",py:"Wǒ zài biànlì shāngdiàn mǎi le yì běn zázhì.",j:"コンビニで雑誌を一冊買いました。",e:"I bought a magazine at the convenience store.",k:"편의점에서 잡지를 한 권 샀습니다."}},
{w:"信封",py:"xìnfēng",zy:"ㄒㄧㄣˋ ㄈㄥ",c:"名",m:{j:"封筒",e:"envelope",k:"봉투"},ex:{z:"我要買信封跟郵票。",py:"Wǒ yào mǎi xìnfēng gēn yóupiào.",j:"封筒と切手を買いたいです。",e:"I want to buy envelopes and stamps.",k:"봉투와 우표를 사려고 합니다."}},
{w:"郵票",py:"yóupiào",zy:"ㄧㄡˊ ㄆㄧㄠˋ",c:"名",m:{j:"切手",e:"stamp",k:"우표"},ex:{z:"這張郵票很可愛。",py:"Zhè zhāng yóupiào hěn kě'ài.",j:"この切手はとてもかわいいです。",e:"This stamp is very cute.",k:"이 우표는 아주 귀엽습니다."}},
{w:"盒子",py:"hézi",zy:"ㄏㄜˊ ˙ㄗ",c:"名",m:{j:"箱",e:"box",k:"상자"},ex:{z:"盒子裡有什麼？",py:"Hézi lǐ yǒu shénme?",j:"箱の中に何がありますか。",e:"What is in the box?",k:"상자 안에 무엇이 있습니까?"}},
{w:"瓶子",py:"píngzi",zy:"ㄆㄧㄥˊ ˙ㄗ",c:"名",m:{j:"瓶・ボトル",e:"bottle",k:"병"},ex:{z:"桌上有一個瓶子。",py:"Zhuō shàng yǒu yí ge píngzi.",j:"テーブルの上に瓶が1つあります。",e:"There is a bottle on the table.",k:"탁자 위에 병이 하나 있습니다."}},
{w:"杯子",py:"bēizi",zy:"ㄅㄟ ˙ㄗ",c:"名",m:{j:"コップ・カップ",e:"cup; glass",k:"컵, 잔"},ex:{z:"這個杯子是我的。",py:"Zhège bēizi shì wǒ de.",j:"このコップは私のです。",e:"This cup is mine.",k:"이 컵은 제 것입니다."}},
{w:"中午",py:"zhōngwǔ",zy:"ㄓㄨㄥ ㄨˇ",c:"名",m:{j:"昼・正午",e:"noon",k:"정오, 점심때"},ex:{z:"我中午吃便當。",py:"Wǒ zhōngwǔ chī biàndāng.",j:"昼はお弁当を食べます。",e:"I eat a lunch box at noon.",k:"저는 점심에 도시락을 먹습니다."}},
{w:"分鐘",py:"fēnzhōng",zy:"ㄈㄣ ㄓㄨㄥ",c:"量",m:{j:"〜分間",e:"minute",k:"~분"},ex:{z:"從我家到車站要十分鐘。",py:"Cóng wǒ jiā dào chēzhàn yào shí fēnzhōng.",j:"家から駅まで10分かかります。",e:"It takes ten minutes from my home to the station.",k:"우리 집에서 역까지 10분 걸립니다."}},
{w:"臉",py:"liǎn",zy:"ㄌㄧㄢˇ",c:"名",m:{j:"顔",e:"face",k:"얼굴"},ex:{z:"我每天早上洗臉。",py:"Wǒ měitiān zǎoshang xǐ liǎn.",j:"私は毎朝顔を洗います。",e:"I wash my face every morning.",k:"저는 매일 아침 세수를 합니다."}},
{w:"裙子",py:"qúnzi",zy:"ㄑㄩㄣˊ ˙ㄗ",c:"名",m:{j:"スカート",e:"skirt",k:"치마"},ex:{z:"她今天穿白色的裙子。",py:"Tā jīntiān chuān báisè de qúnzi.",j:"彼女は今日、白いスカートをはいています。",e:"She is wearing a white skirt today.",k:"그녀는 오늘 흰색 치마를 입고 있습니다."}},
{w:"鼻子",py:"bízi",zy:"ㄅㄧˊ ˙ㄗ",c:"名",m:{j:"鼻",e:"nose",k:"코"},ex:{z:"感冒了，鼻子不舒服。",py:"Gǎnmào le, bízi bù shūfú.",j:"風邪をひいて、鼻の調子が悪いです。",e:"I have a cold and my nose feels uncomfortable.",k:"감기에 걸려서 코가 불편합니다."}},
{w:"頭髮",py:"tóufǎ",zy:"ㄊㄡˊ ㄈㄚˇ",c:"名",m:{j:"髪の毛",e:"hair",k:"머리카락"},ex:{z:"她的頭髮很長。",py:"Tā de tóufǎ hěn cháng.",j:"彼女の髪はとても長いです。",e:"Her hair is very long.",k:"그녀의 머리카락은 아주 깁니다."}},
// ── 自然（第二輪追加） ──
{w:"太陽",py:"tàiyáng",zy:"ㄊㄞˋ ㄧㄤˊ",c:"名",m:{j:"太陽",e:"sun",k:"태양, 해"},ex:{z:"太陽出來了。",py:"Tàiyáng chūlái le.",j:"太陽が出てきました。",e:"The sun has come out.",k:"해가 나왔습니다."}},
{w:"月亮",py:"yuèliàng",zy:"ㄩㄝˋ ㄌㄧㄤˋ",c:"名",m:{j:"月",e:"moon",k:"달"},ex:{z:"今天晚上的月亮很漂亮。",py:"Jīntiān wǎnshàng de yuèliàng hěn piàoliàng.",j:"今夜の月はとてもきれいです。",e:"The moon is very beautiful tonight.",k:"오늘 밤 달이 아주 예쁩니다."}},
{w:"星星",py:"xīngxing",zy:"ㄒㄧㄥ ˙ㄒㄧㄥ",c:"名",m:{j:"星",e:"star",k:"별"},ex:{z:"山上可以看到很多星星。",py:"Shān shàng kěyǐ kàndào hěn duō xīngxing.",j:"山の上では星がたくさん見えます。",e:"You can see many stars on the mountain.",k:"산 위에서는 별을 많이 볼 수 있습니다."}},
{w:"天空",py:"tiānkōng",zy:"ㄊㄧㄢ ㄎㄨㄥ",c:"名",m:{j:"空",e:"sky",k:"하늘"},ex:{z:"今天的天空很藍。",py:"Jīntiān de tiānkōng hěn lán.",j:"今日の空はとても青いです。",e:"The sky is very blue today.",k:"오늘 하늘이 아주 파랗습니다."}},
{w:"山",py:"shān",zy:"ㄕㄢ",c:"名",m:{j:"山",e:"mountain",k:"산"},ex:{z:"台灣有很多高山。",py:"Táiwān yǒu hěn duō gāo shān.",j:"台湾には高い山がたくさんあります。",e:"Taiwan has many high mountains.",k:"대만에는 높은 산이 많습니다."}},
{w:"海",py:"hǎi",zy:"ㄏㄞˇ",c:"名",m:{j:"海",e:"sea",k:"바다"},ex:{z:"週末我們去看海。",py:"Zhōumò wǒmen qù kàn hǎi.",j:"週末、私たちは海を見に行きます。",e:"We are going to see the sea this weekend.",k:"주말에 우리는 바다를 보러 갑니다."}},
{w:"河",py:"hé",zy:"ㄏㄜˊ",c:"名",m:{j:"川",e:"river",k:"강"},ex:{z:"河的旁邊有一個公園。",py:"Hé de pángbiān yǒu yí ge gōngyuán.",j:"川のそばに公園があります。",e:"There is a park beside the river.",k:"강 옆에 공원이 하나 있습니다."}},
{w:"樹",py:"shù",zy:"ㄕㄨˋ",c:"名",m:{j:"木",e:"tree",k:"나무"},ex:{z:"公園裡有很多樹。",py:"Gōngyuán lǐ yǒu hěn duō shù.",j:"公園には木がたくさんあります。",e:"There are many trees in the park.",k:"공원에는 나무가 많습니다."}},
{w:"花",py:"huā",zy:"ㄏㄨㄚ",c:"名",m:{j:"花",e:"flower",k:"꽃"},ex:{z:"這些花很漂亮。",py:"Zhèxiē huā hěn piàoliàng.",j:"これらの花はとてもきれいです。",e:"These flowers are very beautiful.",k:"이 꽃들은 아주 예쁩니다."}},
{w:"草",py:"cǎo",zy:"ㄘㄠˇ",c:"名",m:{j:"草",e:"grass",k:"풀"},ex:{z:"貓在草上睡覺。",py:"Māo zài cǎo shàng shuìjiào.",j:"猫が草の上で寝ています。",e:"The cat is sleeping on the grass.",k:"고양이가 풀 위에서 자고 있습니다."}},
// ── 乗り物（第二輪追加） ──
{w:"飛機",py:"fēijī",zy:"ㄈㄟ ㄐㄧ",c:"名",m:{j:"飛行機",e:"airplane",k:"비행기"},ex:{z:"我坐飛機去日本。",py:"Wǒ zuò fēijī qù Rìběn.",j:"飛行機で日本へ行きます。",e:"I go to Japan by plane.",k:"비행기를 타고 일본에 갑니다."}},
{w:"腳踏車",py:"jiǎotàchē",zy:"ㄐㄧㄠˇ ㄊㄚˋ ㄔㄜ",c:"名",m:{j:"自転車",e:"bicycle",k:"자전거"},ex:{z:"我每天騎腳踏車上班。",py:"Wǒ měitiān qí jiǎotàchē shàngbān.",j:"私は毎日自転車で出勤します。",e:"I ride a bicycle to work every day.",k:"저는 매일 자전거를 타고 출근합니다."}},
{w:"車",py:"chē",zy:"ㄔㄜ",c:"名",m:{j:"車",e:"car; vehicle",k:"차"},ex:{z:"路上車很多。",py:"Lù shàng chē hěn duō.",j:"道路には車が多いです。",e:"There are many cars on the road.",k:"길에 차가 많습니다."}},
// ── 動作（第二輪追加） ──
{w:"等",py:"děng",zy:"ㄉㄥˇ",c:"動",m:{j:"待つ",e:"to wait",k:"기다리다"},ex:{z:"請等我五分鐘。",py:"Qǐng děng wǒ wǔ fēnzhōng.",j:"5分待ってください。",e:"Please wait for me for five minutes.",k:"5분만 기다려 주세요."}},
{w:"幫",py:"bāng",zy:"ㄅㄤ",c:"動",m:{j:"手伝う・〜してあげる",e:"to help",k:"돕다, ~해 주다"},ex:{z:"你可以幫我拿嗎？",py:"Nǐ kěyǐ bāng wǒ ná ma?",j:"持つのを手伝ってもらえますか。",e:"Can you help me carry this?",k:"이것 좀 들어 줄 수 있어요?"}},
{w:"賣",py:"mài",zy:"ㄇㄞˋ",c:"動",m:{j:"売る",e:"to sell",k:"팔다"},ex:{z:"這家店賣水果。",py:"Zhè jiā diàn mài shuǐguǒ.",j:"この店は果物を売っています。",e:"This shop sells fruit.",k:"이 가게는 과일을 팝니다."}},
{w:"租",py:"zū",zy:"ㄗㄨ",c:"動",m:{j:"借りる（賃貸）・貸す",e:"to rent",k:"세내다, 빌리다"},ex:{z:"我在台北租房子。",py:"Wǒ zài Táiběi zū fángzi.",j:"私は台北で家を借りています。",e:"I rent a place in Taipei.",k:"저는 타이베이에서 집을 세내어 삽니다."}},
{w:"飛",py:"fēi",zy:"ㄈㄟ",c:"動",m:{j:"飛ぶ",e:"to fly",k:"날다"},ex:{z:"鳥在天空飛。",py:"Niǎo zài tiānkōng fēi.",j:"鳥が空を飛んでいます。",e:"Birds are flying in the sky.",k:"새가 하늘을 날고 있습니다."}},
{w:"跳",py:"tiào",zy:"ㄊㄧㄠˋ",c:"動",m:{j:"跳ぶ・跳ねる",e:"to jump",k:"뛰다, 점프하다"},ex:{z:"貓跳到桌子上。",py:"Māo tiào dào zhuōzi shàng.",j:"猫がテーブルの上に飛び乗りました。",e:"The cat jumped onto the table.",k:"고양이가 탁자 위로 뛰어올랐습니다."}},
{w:"畫",py:"huà",zy:"ㄏㄨㄚˋ",c:"動",m:{j:"描く",e:"to draw; to paint",k:"그리다"},ex:{z:"妹妹很會畫畫。",py:"Mèimei hěn huì huàhuà.",j:"妹は絵を描くのがとても上手です。",e:"My younger sister is very good at drawing.",k:"여동생은 그림을 아주 잘 그립니다."}},
{w:"推",py:"tuī",zy:"ㄊㄨㄟ",c:"動",m:{j:"押す",e:"to push",k:"밀다"},ex:{z:"這個門要推，不要拉。",py:"Zhège mén yào tuī, bú yào lā.",j:"このドアは引かずに押してください。",e:"Push this door, do not pull it.",k:"이 문은 당기지 말고 미세요."}},
{w:"拉",py:"lā",zy:"ㄌㄚ",c:"動",m:{j:"引く・引っ張る",e:"to pull",k:"당기다, 끌다"},ex:{z:"弟弟拉我的手。",py:"Dìdi lā wǒ de shǒu.",j:"弟が私の手を引っ張ります。",e:"My younger brother pulls my hand.",k:"남동생이 제 손을 잡아끕니다."}},
{w:"抱",py:"bào",zy:"ㄅㄠˋ",c:"動",m:{j:"抱く・抱っこする",e:"to hug; to hold",k:"안다"},ex:{z:"媽媽抱著嬰兒。",py:"Māma bào zhe yīng'ér.",j:"お母さんが赤ちゃんを抱いています。",e:"The mother is holding the baby.",k:"엄마가 아기를 안고 있습니다."}},
{w:"脫",py:"tuō",zy:"ㄊㄨㄛ",c:"動",m:{j:"脱ぐ",e:"to take off",k:"벗다"},ex:{z:"進門要脫鞋子。",py:"Jìn mén yào tuō xiézi.",j:"家に入るときは靴を脱ぎます。",e:"You need to take off your shoes when entering.",k:"집에 들어갈 때는 신발을 벗어야 합니다."}},
{w:"戴",py:"dài",zy:"ㄉㄞˋ",c:"動",m:{j:"（帽子・眼鏡などを）かける・かぶる",e:"to wear (glasses, hat)",k:"쓰다, 착용하다"},ex:{z:"他今天戴眼鏡。",py:"Tā jīntiān dài yǎnjìng.",j:"彼は今日、眼鏡をかけています。",e:"He is wearing glasses today.",k:"그는 오늘 안경을 쓰고 있습니다."}},
// ── 状態・形容（第二輪追加） ──
{w:"乾",py:"gān",zy:"ㄍㄢ",c:"形",m:{j:"乾いている",e:"dry",k:"마르다, 건조하다"},ex:{z:"衣服還沒乾。",py:"Yīfú hái méi gān.",j:"服はまだ乾いていません。",e:"The clothes are not dry yet.",k:"옷이 아직 마르지 않았습니다."}},
{w:"濕",py:"shī",zy:"ㄕ",c:"形",m:{j:"濡れている・湿っている",e:"wet",k:"젖다, 습하다"},ex:{z:"下雨了，我的鞋子濕了。",py:"Xià yǔ le, wǒ de xiézi shī le.",j:"雨が降って、靴が濡れました。",e:"It rained and my shoes got wet.",k:"비가 와서 신발이 젖었습니다."}},
{w:"亮",py:"liàng",zy:"ㄌㄧㄤˋ",c:"形",m:{j:"明るい",e:"bright",k:"밝다"},ex:{z:"這個房間很亮。",py:"Zhège fángjiān hěn liàng.",j:"この部屋はとても明るいです。",e:"This room is very bright.",k:"이 방은 아주 밝습니다."}},
{w:"暗",py:"àn",zy:"ㄢˋ",c:"形",m:{j:"暗い",e:"dark",k:"어둡다"},ex:{z:"房間太暗了。",py:"Fángjiān tài àn le.",j:"部屋が暗すぎます。",e:"The room is too dark.",k:"방이 너무 어둡습니다."}},
{w:"滿",py:"mǎn",zy:"ㄇㄢˇ",c:"形",m:{j:"いっぱいである",e:"full",k:"가득하다"},ex:{z:"杯子滿了。",py:"Bēizi mǎn le.",j:"コップがいっぱいになりました。",e:"The cup is full.",k:"컵이 가득 찼습니다."}},
{w:"空",py:"kōng",zy:"ㄎㄨㄥ",c:"形",m:{j:"空っぽの",e:"empty",k:"비다"},ex:{z:"瓶子是空的。",py:"Píngzi shì kōng de.",j:"瓶は空です。",e:"The bottle is empty.",k:"병이 비어 있습니다."}},
{w:"輕",py:"qīng",zy:"ㄑㄧㄥ",c:"形",m:{j:"軽い",e:"light (weight)",k:"가볍다"},ex:{z:"這個包包很輕。",py:"Zhège bāobāo hěn qīng.",j:"このかばんはとても軽いです。",e:"This bag is very light.",k:"이 가방은 아주 가볍습니다."}},
{w:"重",py:"zhòng",zy:"ㄓㄨㄥˋ",c:"形",m:{j:"重い",e:"heavy",k:"무겁다"},ex:{z:"行李太重了。",py:"Xínglǐ tài zhòng le.",j:"荷物が重すぎます。",e:"The luggage is too heavy.",k:"짐이 너무 무겁습니다."}},
{w:"厚",py:"hòu",zy:"ㄏㄡˋ",c:"形",m:{j:"厚い",e:"thick",k:"두껍다"},ex:{z:"這本書很厚。",py:"Zhè běn shū hěn hòu.",j:"この本はとても厚いです。",e:"This book is very thick.",k:"이 책은 아주 두껍습니다."}},
{w:"薄",py:"bó",zy:"ㄅㄛˊ",c:"形",m:{j:"薄い",e:"thin (flat things)",k:"얇다"},ex:{z:"這件外套太薄了。",py:"Zhè jiàn wàitào tài bó le.",j:"このコートは薄すぎます。",e:"This coat is too thin.",k:"이 외투는 너무 얇습니다."}},
{w:"圓",py:"yuán",zy:"ㄩㄢˊ",c:"形",m:{j:"丸い",e:"round",k:"둥글다"},ex:{z:"月亮又圓又亮。",py:"Yuèliàng yòu yuán yòu liàng.",j:"月は丸くて明るいです。",e:"The moon is round and bright.",k:"달이 둥글고 밝습니다."}},
{w:"方",py:"fāng",zy:"ㄈㄤ",c:"形",m:{j:"四角い",e:"square",k:"네모나다"},ex:{z:"這個桌子是方的。",py:"Zhège zhuōzi shì fāng de.",j:"このテーブルは四角いです。",e:"This table is square.",k:"이 탁자는 네모납니다."}},
{w:"手錶",py:"shǒubiǎo",zy:"ㄕㄡˇ ㄅㄧㄠˇ",c:"名",m:{j:"腕時計",e:"watch",k:"손목시계"},ex:{z:"這支手錶很貴。",py:"Zhè zhī shǒubiǎo hěn guì.",j:"この腕時計はとても高いです。",e:"This watch is very expensive.",k:"이 손목시계는 아주 비쌉니다."}},
// ── 位置・時間（第二輪追加） ──
{w:"左邊",py:"zuǒbiān",zy:"ㄗㄨㄛˇ ㄅㄧㄢ",c:"名",m:{j:"左側",e:"left side",k:"왼쪽"},ex:{z:"便利商店在銀行的左邊。",py:"Biànlì shāngdiàn zài yínháng de zuǒbiān.",j:"コンビニは銀行の左側にあります。",e:"The convenience store is on the left of the bank.",k:"편의점은 은행 왼쪽에 있습니다."}},
{w:"右邊",py:"yòubiān",zy:"ㄧㄡˋ ㄅㄧㄢ",c:"名",m:{j:"右側",e:"right side",k:"오른쪽"},ex:{z:"廁所在右邊。",py:"Cèsuǒ zài yòubiān.",j:"トイレは右側にあります。",e:"The restroom is on the right.",k:"화장실은 오른쪽에 있습니다."}},
{w:"上面",py:"shàngmiàn",zy:"ㄕㄤˋ ㄇㄧㄢˋ",c:"名",m:{j:"上・上の方",e:"on top; above",k:"위, 위쪽"},ex:{z:"書在桌子上面。",py:"Shū zài zhuōzi shàngmiàn.",j:"本はテーブルの上にあります。",e:"The book is on the table.",k:"책은 탁자 위에 있습니다."}},
{w:"下面",py:"xiàmiàn",zy:"ㄒㄧㄚˋ ㄇㄧㄢˋ",c:"名",m:{j:"下・下の方",e:"below; underneath",k:"아래, 밑"},ex:{z:"貓在椅子下面。",py:"Māo zài yǐzi xiàmiàn.",j:"猫は椅子の下にいます。",e:"The cat is under the chair.",k:"고양이는 의자 밑에 있습니다."}},
{w:"這裡",py:"zhèlǐ",zy:"ㄓㄜˋ ㄌㄧˇ",c:"代",m:{j:"ここ",e:"here",k:"여기"},ex:{z:"請在這裡等一下。",py:"Qǐng zài zhèlǐ děng yíxià.",j:"ここで少し待ってください。",e:"Please wait here for a moment.",k:"여기서 잠시 기다려 주세요."}},
{w:"那裡",py:"nàlǐ",zy:"ㄋㄚˋ ㄌㄧˇ",c:"代",m:{j:"そこ・あそこ",e:"there",k:"거기, 저기"},ex:{z:"車站在那裡。",py:"Chēzhàn zài nàlǐ.",j:"駅はあそこです。",e:"The station is over there.",k:"역은 저기에 있습니다."}},
{w:"剛才",py:"gāngcái",zy:"ㄍㄤ ㄘㄞˊ",c:"副",m:{j:"さっき",e:"just now",k:"방금, 아까"},ex:{z:"剛才有人打電話給你。",py:"Gāngcái yǒu rén dǎ diànhuà gěi nǐ.",j:"さっき、誰かからあなたに電話がありました。",e:"Someone called you just now.",k:"방금 누가 당신에게 전화했습니다."}},
{w:"馬路",py:"mǎlù",zy:"ㄇㄚˇ ㄌㄨˋ",c:"名",m:{j:"道路・大通り",e:"road; street",k:"길, 도로"},ex:{z:"過馬路要小心。",py:"Guò mǎlù yào xiǎoxīn.",j:"道路を渡るときは気をつけてください。",e:"Be careful when crossing the road.",k:"길을 건널 때는 조심해야 합니다."}},
{w:"路口",py:"lùkǒu",zy:"ㄌㄨˋ ㄎㄡˇ",c:"名",m:{j:"交差点・曲がり角",e:"intersection",k:"교차로, 길목"},ex:{z:"在下一個路口右轉。",py:"Zài xià yí ge lùkǒu yòuzhuǎn.",j:"次の交差点を右に曲がります。",e:"Turn right at the next intersection.",k:"다음 교차로에서 우회전하세요."}},
// ── 人・呼び方（第二輪追加） ──
{w:"同學",py:"tóngxué",zy:"ㄊㄨㄥˊ ㄒㄩㄝˊ",c:"名",m:{j:"クラスメート・同級生",e:"classmate",k:"동창, 학우"},ex:{z:"他是我的大學同學。",py:"Tā shì wǒ de dàxué tóngxué.",j:"彼は私の大学の同級生です。",e:"He is my university classmate.",k:"그는 제 대학 동창입니다."}},
{w:"胖",py:"pàng",zy:"ㄆㄤˋ",c:"形",m:{j:"太っている",e:"fat; chubby",k:"뚱뚱하다"},ex:{z:"我最近胖了。",py:"Wǒ zuìjìn pàng le.",j:"最近太りました。",e:"I have gained weight recently.",k:"저는 요즘 살이 쪘습니다."}},
{w:"瘦",py:"shòu",zy:"ㄕㄡˋ",c:"形",m:{j:"痩せている",e:"thin; slim",k:"마르다, 날씬하다"},ex:{z:"他吃很多，可是很瘦。",py:"Tā chī hěn duō, kěshì hěn shòu.",j:"彼はたくさん食べるのに痩せています。",e:"He eats a lot but is very thin.",k:"그는 많이 먹는데도 아주 말랐습니다."}},
{w:"客人",py:"kèrén",zy:"ㄎㄜˋ ㄖㄣˊ",c:"名",m:{j:"お客さん",e:"guest; customer",k:"손님"},ex:{z:"今天店裡客人很多。",py:"Jīntiān diàn lǐ kèrén hěn duō.",j:"今日は店にお客さんが多いです。",e:"There are many customers in the shop today.",k:"오늘 가게에 손님이 많습니다."}},
{w:"老闆娘",py:"lǎobǎnniáng",zy:"ㄌㄠˇ ㄅㄢˇ ㄋㄧㄤˊ",c:"名",m:{j:"女将さん・女性店主",e:"female boss; boss's wife",k:"여사장, 안주인"},ex:{z:"老闆娘給了我一杯茶。",py:"Lǎobǎnniáng gěi le wǒ yì bēi chá.",j:"女将さんがお茶を一杯くれました。",e:"The boss's wife gave me a cup of tea.",k:"여사장님이 저에게 차 한 잔을 주셨습니다."}},
{w:"小孩",py:"xiǎohái",zy:"ㄒㄧㄠˇ ㄏㄞˊ",c:"名",m:{j:"子ども",e:"child; kid",k:"아이"},ex:{z:"公園裡有很多小孩。",py:"Gōngyuán lǐ yǒu hěn duō xiǎohái.",j:"公園には子どもがたくさんいます。",e:"There are many children in the park.",k:"공원에는 아이들이 많습니다."}},
{w:"嬰兒",py:"yīng'ér",zy:"ㄧㄥ ㄦˊ",c:"名",m:{j:"赤ちゃん",e:"baby",k:"아기"},ex:{z:"嬰兒在睡覺。",py:"Yīng'ér zài shuìjiào.",j:"赤ちゃんが寝ています。",e:"The baby is sleeping.",k:"아기가 자고 있습니다."}},
// ── 生活動詞・娯楽（第二輪追加） ──
{w:"上網",py:"shàngwǎng",zy:"ㄕㄤˋ ㄨㄤˇ",c:"動",m:{j:"ネットをする",e:"to go online",k:"인터넷을 하다"},ex:{z:"我每天晚上上網。",py:"Wǒ měitiān wǎnshàng shàngwǎng.",j:"私は毎晩ネットをします。",e:"I go online every night.",k:"저는 매일 밤 인터넷을 합니다."}},
{w:"打球",py:"dǎqiú",zy:"ㄉㄚˇ ㄑㄧㄡˊ",c:"動",m:{j:"球技をする",e:"to play ball",k:"공놀이를 하다, 구기를 하다"},ex:{z:"週末我跟朋友去打球。",py:"Zhōumò wǒ gēn péngyǒu qù dǎqiú.",j:"週末は友達と球技をしに行きます。",e:"I play ball with my friends on weekends.",k:"주말에 친구와 공놀이를 하러 갑니다."}},
{w:"跑步",py:"pǎobù",zy:"ㄆㄠˇ ㄅㄨˋ",c:"動",m:{j:"ジョギングする・走る",e:"to run; to jog",k:"달리기하다"},ex:{z:"我早上去公園跑步。",py:"Wǒ zǎoshang qù gōngyuán pǎobù.",j:"朝、公園へジョギングに行きます。",e:"I go jogging in the park in the morning.",k:"아침에 공원에 달리기하러 갑니다."}},
{w:"散步",py:"sànbù",zy:"ㄙㄢˋ ㄅㄨˋ",c:"動",m:{j:"散歩する",e:"to take a walk",k:"산책하다"},ex:{z:"吃飯以後我們去散步。",py:"Chīfàn yǐhòu wǒmen qù sànbù.",j:"食事の後、私たちは散歩に行きます。",e:"We take a walk after dinner.",k:"밥을 먹은 후에 우리는 산책하러 갑니다."}},
{w:"點菜",py:"diǎncài",zy:"ㄉㄧㄢˇ ㄘㄞˋ",c:"動",m:{j:"料理を注文する",e:"to order food",k:"요리를 주문하다"},ex:{z:"你們要點菜了嗎？",py:"Nǐmen yào diǎncài le ma?",j:"ご注文はお決まりですか。",e:"Are you ready to order?",k:"주문하시겠어요?"}},
{w:"外帶",py:"wàidài",zy:"ㄨㄞˋ ㄉㄞˋ",c:"動",m:{j:"テイクアウトする",e:"to take out (food)",k:"포장하다, 테이크아웃하다"},ex:{z:"一杯珍珠奶茶，外帶。",py:"Yì bēi zhēnzhū nǎichá, wàidài.",j:"タピオカミルクティーを一つ、テイクアウトで。",e:"One bubble tea, to go.",k:"버블티 한 잔, 포장이요."}},
{w:"電影",py:"diànyǐng",zy:"ㄉㄧㄢˋ ㄧㄥˇ",c:"名",m:{j:"映画",e:"movie",k:"영화"},ex:{z:"我們晚上去看電影。",py:"Wǒmen wǎnshàng qù kàn diànyǐng.",j:"私たちは夜、映画を見に行きます。",e:"We are going to see a movie tonight.",k:"우리는 밤에 영화를 보러 갑니다."}},
{w:"音樂",py:"yīnyuè",zy:"ㄧㄣ ㄩㄝˋ",c:"名",m:{j:"音楽",e:"music",k:"음악"},ex:{z:"我喜歡聽音樂。",py:"Wǒ xǐhuān tīng yīnyuè.",j:"私は音楽を聴くのが好きです。",e:"I like listening to music.",k:"저는 음악 듣는 것을 좋아합니다."}},
{w:"蛋糕",py:"dàngāo",zy:"ㄉㄢˋ ㄍㄠ",c:"名",m:{j:"ケーキ",e:"cake",k:"케이크"},ex:{z:"生日要吃蛋糕。",py:"Shēngrì yào chī dàngāo.",j:"誕生日にはケーキを食べます。",e:"We eat cake on birthdays.",k:"생일에는 케이크를 먹습니다."}},
{w:"地方",py:"dìfāng",zy:"ㄉㄧˋ ㄈㄤ",c:"名",m:{j:"場所・ところ",e:"place",k:"곳, 장소"},ex:{z:"台灣是一個很漂亮的地方。",py:"Táiwān shì yí ge hěn piàoliàng de dìfāng.",j:"台湾はとてもきれいなところです。",e:"Taiwan is a very beautiful place.",k:"대만은 아주 아름다운 곳입니다."}},
// ── 季節（第二輪追加） ──
{w:"春天",py:"chūntiān",zy:"ㄔㄨㄣ ㄊㄧㄢ",c:"名",m:{j:"春",e:"spring",k:"봄"},ex:{z:"春天的花很漂亮。",py:"Chūntiān de huā hěn piàoliàng.",j:"春の花はとてもきれいです。",e:"The flowers in spring are very beautiful.",k:"봄의 꽃은 아주 예쁩니다."}},
{w:"秋天",py:"qiūtiān",zy:"ㄑㄧㄡ ㄊㄧㄢ",c:"名",m:{j:"秋",e:"autumn; fall",k:"가을"},ex:{z:"秋天不熱也不冷。",py:"Qiūtiān bú rè yě bù lěng.",j:"秋は暑くも寒くもありません。",e:"Autumn is neither hot nor cold.",k:"가을은 덥지도 춥지도 않습니다."}},
];
if (typeof module !== "undefined") module.exports = { VOCAB_L1 };
