// StayTW — Level 6 (精通級) 追加詞彙 その1。
// 読みは手で打っていない:単語の注音は萌典(教育部)そのまま、拼音は py2zy の音節表を逆引き。
// 例文の拼音は長い語から萌典に聞いて熟語単位で確定させ、一/不 は連続変調を通してある。
//   生成: python3 scripts/new-vocab.py <batch.json>
// pro:1 = 2026-09 以降に足した語。既存の 1,859 語は無料のまま、ここから先が Premium。
const VOCAB_L6_B = [
{"w": "潛移默化", "py": "qiányímòhuà", "zy": "ㄑㄧㄢˊ ㄧˊ ㄇㄛˋ ㄏㄨㄚˋ", "c": "成", "m": {"j": "知らないうちに影響を受けて変わる", "e": "to change someone imperceptibly", "k": "모르는 사이에 감화되다"}, "ex": {"z": "好的環境會潛移默化改變一個孩子。", "py": "hǎo de huán jìng huì qián yí mò huà gǎi biàn yì ge hái zi", "j": "よい環境は知らないうちに子どもを変える。", "e": "A good environment changes a child without them noticing.", "k": "좋은 환경은 모르는 사이에 아이를 바꾼다."}, "pro": 1},
{"w": "深思熟慮", "py": "shēnsīshóulǜ", "zy": "ㄕㄣ ㄙ ㄕㄡˊ ㄌㄩˋ", "c": "成", "m": {"j": "じっくり考え抜く", "e": "to think something through", "k": "깊이 숙고하다"}, "ex": {"z": "這個決定是深思熟慮後的結果。", "py": "zhè ge jué dìng shì shēn sī shóu lǜ hòu de jié guǒ", "j": "この決定はじっくり考え抜いた結果だ。", "e": "This decision came after thinking it through.", "k": "이 결정은 깊이 숙고한 결과다."}, "pro": 1},
{"w": "息息相關", "py": "xíxíxiāngguān", "zy": "ㄒㄧˊ ㄒㄧˊ ㄒㄧㄤ ㄍㄨㄢ", "c": "成", "m": {"j": "密接に関わっている", "e": "to be closely bound up with", "k": "밀접하게 관련되다"}, "ex": {"z": "物價與民眾生活息息相關。", "py": "wù jià yǔ mín zhòng shēng huó xí xí xiāng guān", "j": "物価は市民の生活と密接に関わっている。", "e": "Prices are closely bound up with people's daily lives.", "k": "물가는 시민 생활과 밀접하게 관련된다."}, "pro": 1},
{"w": "層出不窮", "py": "céngchūbùqióng", "zy": "ㄘㄥˊ ㄔㄨ ㄅㄨˋ ㄑㄩㄥˊ", "c": "成", "m": {"j": "次から次へと現れて尽きない", "e": "to emerge endlessly", "k": "끊임없이 나타나다"}, "ex": {"z": "詐騙手法層出不窮，大家要小心。", "py": "zhà piàn shǒu fǎ céng chū bù qióng dà jiā yào xiǎo xīn", "j": "詐欺の手口は次々に現れるので、気をつけて。", "e": "Scam tactics keep appearing, so stay alert.", "k": "사기 수법이 끊임없이 나타나니 조심하세요."}, "pro": 1},
{"w": "舉足輕重", "py": "jǔzúqīngzhòng", "zy": "ㄐㄩˇ ㄗㄨˊ ㄑㄧㄥ ㄓㄨㄥˋ", "c": "成", "m": {"j": "きわめて重要な位置を占める", "e": "to carry decisive weight", "k": "매우 중요한 위치에 있다"}, "ex": {"z": "半導體在台灣經濟中舉足輕重。", "py": "bàn dǎo tǐ zài tái wān jīng jì zhōng jǔ zú qīng zhòng", "j": "半導体は台湾経済で極めて重要だ。", "e": "Semiconductors carry decisive weight in Taiwan's economy.", "k": "반도체는 대만 경제에서 매우 중요하다."}, "pro": 1},
{"w": "名副其實", "py": "míngfùqíshí", "zy": "ㄇㄧㄥˊ ㄈㄨˋ ㄑㄧˊ ㄕˊ", "c": "成", "m": {"j": "評判どおりで中身が伴う", "e": "to live up to the name", "k": "명실상부하다"}, "ex": {"z": "這裡是名副其實的美食天堂。", "py": "zhè lǐ shì míng fù qí shí de měi shí tiān táng", "j": "ここは評判どおりのグルメ天国だ。", "e": "This place really does live up to its name as a food paradise.", "k": "이곳은 명실상부한 미식 천국이다."}, "pro": 1},
{"w": "雪上加霜", "py": "xuěshàngjiāshuāng", "zy": "ㄒㄩㄝˇ ㄕㄤˋ ㄐㄧㄚ ㄕㄨㄤ", "c": "成", "m": {"j": "悪いことが重なる", "e": "to make a bad situation worse", "k": "엎친 데 덮치다"}, "ex": {"z": "房租又漲，對他來說是雪上加霜。", "py": "fáng zū yòu zhàng duì tā lái shuō shì xuě shàng jiā shuāng", "j": "家賃も上がって、彼には泣きっ面に蜂だ。", "e": "Rent went up too, which made things even worse for him.", "k": "집세까지 올라 그에게는 엎친 데 덮친 격이다."}, "pro": 1},
{"w": "因地制宜", "py": "yīndìzhìyí", "zy": "ㄧㄣ ㄉㄧˋ ㄓˋ ㄧˊ", "c": "成", "m": {"j": "土地の事情に合わせてやり方を決める", "e": "to adapt the method to local conditions", "k": "현지 사정에 맞게 하다"}, "ex": {"z": "政策要因地制宜，不能一體適用。", "py": "zhèng cè yào yīn dì zhì yí bù néng yì tǐ shì yòng", "j": "政策は土地の事情に合わせるべきだ。", "e": "Policy has to fit local conditions, not be applied uniformly.", "k": "정책은 현지 사정에 맞춰야 한다."}, "pro": 1},
{"w": "權衡", "py": "quánhéng", "zy": "ㄑㄩㄢˊ ㄏㄥˊ", "c": "動", "m": {"j": "比べて量る、天秤にかける", "e": "to weigh up", "k": "저울질하다"}, "ex": {"z": "他在權衡兩個方案的利弊。", "py": "tā zài quán héng liǎng ge fāng àn de lì bì", "j": "彼は二つの案の利害を天秤にかけている。", "e": "He is weighing up the pros and cons of the two options.", "k": "그는 두 방안의 장단점을 저울질하고 있다."}, "pro": 1},
{"w": "落實", "py": "luòshí", "zy": "ㄌㄨㄛˋ ㄕˊ", "c": "動", "m": {"j": "実際に行き渡らせる、実行に移す", "e": "to put into practice", "k": "실행에 옮기다"}, "ex": {"z": "政策能不能落實才是關鍵。", "py": "zhèng cè néng bù néng luò shí cái shì guān jiàn", "j": "政策を実行に移せるかどうかが肝心だ。", "e": "Whether the policy is actually put into practice is what matters.", "k": "정책을 실행에 옮길 수 있느냐가 관건이다."}, "pro": 1},
{"w": "剖析", "py": "pǒuxī", "zy": "ㄆㄡˇ ㄒㄧ", "c": "動", "m": {"j": "細かく分けて分析する", "e": "to dissect; to analyse in depth", "k": "낱낱이 분석하다"}, "ex": {"z": "這篇文章剖析了事件的成因。", "py": "zhè piān wén zhāng pǒu xī liǎo shì jiàn de chéng yīn", "j": "この記事は事件の原因を細かく分析している。", "e": "This article dissects the causes of the incident.", "k": "이 글은 사건의 원인을 낱낱이 분석했다."}, "pro": 1},
{"w": "涵蓋", "py": "hángài", "zy": "ㄏㄢˊ ㄍㄞˋ", "c": "動", "m": {"j": "範囲に含む、カバーする", "e": "to cover; to encompass", "k": "포괄하다"}, "ex": {"z": "這門課涵蓋了六個主題。", "py": "zhè mén kè hán gài le liù ge zhǔ tí", "j": "この授業は六つのテーマをカバーしている。", "e": "This course covers six topics.", "k": "이 수업은 여섯 가지 주제를 포괄한다."}, "pro": 1},
{"w": "倡議", "py": "chàngyì", "zy": "ㄔㄤˋ ㄧˋ", "c": "動", "m": {"j": "提唱する、呼びかける", "e": "to advocate; to propose", "k": "제창하다"}, "ex": {"z": "他倡議減少塑膠的使用。", "py": "tā chàng yì jiǎn shǎo sù jiāo de shǐ yòng", "j": "彼はプラスチックの使用を減らそうと呼びかけた。", "e": "He advocated cutting down on plastic use.", "k": "그는 플라스틱 사용을 줄이자고 제창했다."}, "pro": 1},
{"w": "濫用", "py": "lànyòng", "zy": "ㄌㄢˋ ㄩㄥˋ", "c": "動", "m": {"j": "みだりに使う、乱用する", "e": "to abuse; to overuse", "k": "남용하다"}, "ex": {"z": "濫用藥物對身體傷害很大。", "py": "làn yòng yào wù duì shēn tǐ shāng hài hěn dà", "j": "薬物の乱用は体を大きく損なう。", "e": "Abusing medication does serious harm to the body.", "k": "약물 남용은 몸에 큰 해를 끼친다."}, "pro": 1},
{"w": "迫切", "py": "pòqiè", "zy": "ㄆㄛˋ ㄑㄧㄝˋ", "c": "形", "m": {"j": "差し迫っている、切実だ", "e": "urgent; pressing", "k": "절박하다"}, "ex": {"z": "改善交通是很迫切的問題。", "py": "gǎi shàn jiāo tōng shì hěn pò qiè de wèn tí", "j": "交通の改善は差し迫った問題だ。", "e": "Improving transport is an urgent problem.", "k": "교통 개선은 매우 절박한 문제다."}, "pro": 1},
{"w": "凸顯", "py": "túxiǎn", "zy": "ㄊㄨˊ ㄒㄧㄢˇ", "c": "動", "m": {"j": "はっきり浮き立たせる", "e": "to bring into relief; to highlight", "k": "부각하다"}, "ex": {"z": "這件事凸顯了制度的漏洞。", "py": "zhè jiàn shì tú xiǎn le zhì dù de lòu dòng", "j": "この件は制度の抜け穴をはっきり浮き立たせた。", "e": "This case brought the loopholes in the system into relief.", "k": "이 사건은 제도의 허점을 부각했다."}, "pro": 1}
];
if (typeof module !== "undefined") module.exports = { VOCAB_L6_B };
